[staging] Missing Web Links language strings
joomlagerman/joomla pull request #1176
Opened 2020-08-03 19:17 UTC by tecpromotion

Pull Request für Issue #1175 .

### Zusammenfassung der Änderungen

add new strings
translation is missing

### Wo wird der Sprachstring angezeigt / Wie kann getestet werden

backend

2020-08-05 08:54 UTC, zero-24 commented
Es fehlen auch noch drei Dateien?

- [ ] en-GB.plg_editors-xtd_weblink.ini
- [ ] en-GB.plg_editors-xtd_weblink.sys.ini
- [ ] en-GB.plg_system_weblinks.ini
- [ ] en-GB.plg_system_weblinks.sys.ini

<details>
<summary>Click to expand the diff!</summary>

```diff
diff --git a/administrator/language/en-GB/en-GB.plg_editors-xtd_weblink.ini b/administrator/language/en-GB/en-GB.plg_editors-xtd_weblink.ini
new file mode 100644
index 000000000000..471be69a1c5f
--- /dev/null
+++ b/administrator/language/en-GB/en-GB.plg_editors-xtd_weblink.ini
@@ -0,0 +1,8 @@
+; Joomla! Project
+; Copyright (C) 2005 - 2017 Open Source Matters. All rights reserved.
+; License GNU General Public License version 2 or later; see LICENSE.txt, see LICENSE.php
+; Note : All ini files need to be saved as UTF-8
+
+PLG_EDITORS-XTD_WEBLINK="Button - Web Link"
+PLG_EDITORS-XTD_WEBLINK_BUTTON_WEBLINK="Web Link"
+PLG_EDITORS-XTD_WEBLINK_XML_DESCRIPTION="Displays a button to make it possible to insert web links into an Article. Displays a popup allowing you to choose the web link."
diff --git a/administrator/language/en-GB/en-GB.plg_editors-xtd_weblink.sys.ini b/administrator/language/en-GB/en-GB.plg_editors-xtd_weblink.sys.ini
new file mode 100644
index 000000000000..c6446678adeb
--- /dev/null
+++ b/administrator/language/en-GB/en-GB.plg_editors-xtd_weblink.sys.ini
@@ -0,0 +1,7 @@
+; Joomla! Project
+; Copyright (C) 2005 - 2017 Open Source Matters. All rights reserved.
+; License GNU General Public License version 2 or later; see LICENSE.txt, see LICENSE.php
+; Note : All ini files need to be saved as UTF-8
+
+PLG_EDITORS-XTD_WEBLINK="Button - Web Link"
+PLG_EDITORS-XTD_WEBLINK_XML_DESCRIPTION="Displays a button to make it possible to insert web links into an Article. Displays a popup allowing you to choose the web link."
diff --git a/administrator/language/en-GB/en-GB.plg_system_weblinks.ini b/administrator/language/en-GB/en-GB.plg_system_weblinks.ini
new file mode 100644
index 000000000000..a2b402d92d9d
--- /dev/null
+++ b/administrator/language/en-GB/en-GB.plg_system_weblinks.ini
@@ -0,0 +1,8 @@
+; Joomla! Project
+; Copyright (C) 2005 - 2016 Open Source Matters. All rights reserved.
+; License GNU General Public License version 2 or later; see LICENSE.txt, see LICENSE.php
+; Note : All ini files need to be saved as UTF-8
+
+PLG_SYSTEM_WEBLINKS="System - Web Links"
+PLG_SYSTEM_WEBLINKS_STATISTICS="Web Links"
+PLG_SYSTEM_WEBLINKS_XML_DESCRIPTION="This plugin returns statistical information about Joomla! Web Links."
diff --git a/administrator/language/en-GB/en-GB.plg_system_weblinks.sys.ini b/administrator/language/en-GB/en-GB.plg_system_weblinks.sys.ini
new file mode 100644
index 000000000000..f9e4af1b6733
--- /dev/null
+++ b/administrator/language/en-GB/en-GB.plg_system_weblinks.sys.ini
@@ -0,0 +1,7 @@
+; Joomla! Project
+; Copyright (C) 2005 - 2016 Open Source Matters. All rights reserved.
+; License GNU General Public License version 2 or later; see LICENSE.txt, see LICENSE.php
+; Note : All ini files need to be saved as UTF-8
+
+PLG_SYSTEM_WEBLINKS="System - Web Links"
+PLG_SYSTEM_WEBLINKS_XML_DESCRIPTION="This plugin returns statistical information about Joomla! Web Links."

```
</details>

2020-08-19 17:15 UTC, tecpromotion commented
Please check @zero-24

2020-08-19 17:23 UTC, zero-24 requested changes

2020-08-19 17:23 UTC, zero-24 commented on administrator/language/de-DE/de-DE.plg_system_weblinks.sys.ini
> +PLG_SYSTEM_WEBLINKS_XML_DESCRIPTION="TDieses Plugin gibt statistische Informationen über Joomla Weblinks zurück."
```suggestion
PLG_SYSTEM_WEBLINKS_XML_DESCRIPTION="Dieses Plugin gibt statistische Informationen über Joomla Weblinks zurück."
```

2020-08-19 18:06 UTC, zero-24 approved these changes

2020-08-19 18:07 UTC, merged