Improve text in batch modal
joomlagerman/joomla pull request #1283
Opened 2020-10-07 19:20 UTC by max123kl

Pull Request für Issue #1235

### Zusammenfassung der Änderungen
3 Zeilen aktualisiert

2020-10-07 19:27 UTC, tecpromotion commented
@max123kl bitte auch die /language/de-DE/lib_joomla.ini berücksichtigen.

2020-10-07 19:29 UTC, tecpromotion commented on administrator/language/de-DE/lib_joomla.ini
> +JLIB_HTML_BATCH_MENU_LABEL="Kopieren oder Verschieben zur Kategorie"
```suggestion
JLIB_HTML_BATCH_MENU_LABEL="Kopieren oder Verschieben in Kategorie"
```

2020-10-07 19:30 UTC, tecpromotion commented on administrator/language/de-DE/lib_joomla.ini
> +JLIB_HTML_BATCH_MOVE_QUESTION="Aktion ausführen"
```suggestion
JLIB_HTML_BATCH_MOVE_QUESTION="Auszuführende Aktion"
```

2020-10-07 19:30 UTC, tecpromotion requested changes
klingt besser, oder?

2020-10-07 19:56 UTC, max123kl commented
Leider übersehen ;-(
Ist gemacht

2020-10-07 20:50 UTC, max123kl commented
> 
> 
> klingt besser, oder?

Ich hoffe ich habe deine Vorschläge jetzt richtig akzeptiert

2020-10-08 13:41 UTC, zero-24 approved these changes
LGTM @tecpromotion bitte mergen wenn so ok aus deiner Sicht.

2020-10-08 14:26 UTC, tecpromotion approved these changes

2020-10-08 14:26 UTC, tecpromotion approved these changes
thanks @max123kl

2020-10-08 14:27 UTC, merged