[WiP] [4.0] will fix minor color contrast (part 3) "blue"
joomlagerman/joomla pull request #1399
Opened 2020-10-31 18:37 UTC by max123kl

Pull Request für Issue #1392

### Zusammenfassung der Änderungen
Unterstreichung und blaue Textauszeichnung entfernt

eine Datei ev. noch zu bearbeiten:
`/language/de-DE/mod_related_items.ini`

2020-11-01 09:14 UTC, max123kl commented
Bitte den Commit 5e595a0 genau prüfen, habe ich "blind" gemacht. (s. https://github.com/joomlagerman/joomla/issues/1392#issuecomment-719970882)

2020-11-01 20:35 UTC, tecpromotion requested changes
Please check

2020-11-01 20:35 UTC, tecpromotion commented on installation/language/de-DE/joomla.ini
> +INSTL_LANGUAGES_DESC="Die Oberfläche von Joomla! ist in vielen Sprachen verfügbar. Um eine Sprache zu installieren, muss nur die Checkbox vor dem gewünschten Eintrag durch einen Klick markiert werden
```suggestion
INSTL_LANGUAGES_DESC="Die Oberfläche von Joomla! ist in vielen Sprachen verfügbar. Um eine Sprache zu installieren, muss nur die Checkbox vor dem gewünschten Eintrag durch einen Klick markiert werden und anschließend wird die Sprache durch einen Klick auf „Weiter“ installiert.<br /><br /><strong>Hinweis:</strong><br />Diese Operation braucht ca. 10 Sekunden für den Download und die Installation der Sprache.<br />Daher sollten <strong>nicht mehr als 3 Sprachen</strong> gleichzeitig ausgewählt werden, um Zeitüberschreitungen zu verhindern."
```

2020-11-01 20:35 UTC, tecpromotion commented on language/de-DE/mod_articles_category.ini
> +MOD_ARTICLES_CATEGORY_FIELD_MONTHYEARFORMAT_DESC="Bitte ein gültiges Datumsformat eingeben.<br /><br /><<strong>Hinweis:</strong><br />Formatierungsinformationen sind auf https://php.net/date einsehb
```suggestion
MOD_ARTICLES_CATEGORY_FIELD_MONTHYEARFORMAT_DESC="Bitte ein gültiges Datumsformat eingeben.<br /><br /><strong>Hinweis:</strong><br />Formatierungsinformationen sind auf https://php.net/date einsehbar."
```

2020-11-02 05:34 UTC, tecpromotion approved these changes

2020-11-02 05:34 UTC, merged