[WiP] [4.0] will fix text decoration (part 4 of #1369)
joomlagerman/joomla pull request #1402
Opened 2020-11-01 11:51 UTC by max123kl

Pull Request für Issue  #1401

### Zusammenfassung der Änderungen
Folgende Fundstellen sollen aktualisiert werden:

- [ ] ./administrator/language/de-DE/plg_authentication_joomla.sys.ini	line 8:
- [ ] ./administrator/language/de-DE/plg_user_joomla.ini				line 18:
- [ ] ./administrator/language/de-DE/plg_editors-xtd_fields.sys.ini		line 8:
- [ ] ./administrator/language/de-DE/com_languages.ini		line 11:
- [ ] ./administrator/language/de-DE/com_languages.ini		line 14:
- [ ] ./administrator/language/de-DE/com_languages.ini		line 63:
- [ ] ./administrator/language/de-DE/com_languages.ini		line 86:
- [ ] ./administrator/language/de-DE/com_languages.ini		line 93:
- [ ] ./administrator/language/de-DE/com_languages.ini		line 94:
- [ ] ./administrator/language/de-DE/com_languages.ini		line 133:
- [ ] ./administrator/language/de-DE/com_media.ini			line 45:
- [ ] ./administrator/language/de-DE/com_redirect.ini		line 10:
- [ ] ./administrator/language/de-DE/com_redirect.ini		line 11:
- [ ] ./administrator/language/de-DE/plg_system_updatenotification.sys.ini	line 8:
- [ ] ./administrator/language/de-DE/plg_authentication_ldap.sys.ini		line 8:
- [ ] ./administrator/language/de-DE/plg_authentication_joomla.ini		line 9:
- [ ] ./administrator/language/de-DE/plg_finder_content.ini				line 8:
- [ ] ./administrator/language/de-DE/plg_finder_content.sys.ini			line 8:
- [ ] ./administrator/language/de-DE/plg_system_cache.ini				line 8:
- [ ] ./administrator/language/de-DE/plg_editors_tinymce.ini				line 61:
- [ ] ./administrator/language/de-DE/plg_user_joomla.sys.ini				line 8:
- [ ] ./administrator/language/de-DE/mod_login.ini						line 12:
- [ ] ./administrator/language/de-DE/plg_editors-xtd_fields.ini			line 9:
- [ ] ./administrator/language/de-DE/com_banners.ini					line 98:
- [ ] ./administrator/language/de-DE/plg_system_updatenotification.ini		line 20:
- [ ] ./administrator/language/de-DE/mod_login.sys.ini		line 9:
- [ ] ./administrator/language/de-DE/com_config.ini		line 142:
- [ ] ./administrator/language/de-DE/com_config.ini		line 229:
- [ ] ./administrator/language/de-DE/plg_authentication_ldap.ini			line 37:
- [ ] ./administrator/language/de-DE/joomla.ini			line 202:
- [ ] ./administrator/language/de-DE/joomla.ini			line 382:
- [ ] ./administrator/language/de-DE/joomla.ini			line 447:
- [ ] ./administrator/language/de-DE/joomla.ini			                      line 454:
- [ ] ./administrator/language/de-DE/joomla.ini			                      line 456:
- [ ] ./administrator/language/de-DE/plg_authentication_cookie.sys.ini	line 8:
- [ ] ./administrator/language/de-DE/plg_authentication_cookie.ini		line 12:
- [ ] ./administrator/language/de-DE/com_users.ini			line 87:
- [ ] ./administrator/language/de-DE/com_users.ini			line 93:
- [ ] ./language/de-DE/mod_related_items.sys.ini			line 9:
- [ ] ./language/de-DE/mod_feed.ini						line 19:
- [ ] ./language/de-DE/com_media.ini					line 66:
- [ ] ./language/de-DE/mod_related_items.ini				line 7:
- [ ] ./language/de-DE/mod_related_items.ini				line 12:
- [ ] ./language/de-DE/mod_tags_popular.ini				line 15:
- [ ] ./language/de-DE/mod_tags_popular.ini				line 17:
- [ ] ./language/de-DE/mod_articles_category.ini			line 18:
- [ ] ./language/de-DE/mod_articles_category.ini			line 21:
- [ ] ./language/de-DE/mod_articles_category.ini			line 37:
- [ ] ./language/de-DE/mod_articles_categories.ini			line 8:
- [ ] ./language/de-DE/mod_banners.ini					line 12:
- [ ] ./language/de-DE/mod_menu.ini						line 15:

### Wo wird der Sprachstring angezeigt / Wie kann getestet werden
Frontend/Backend

2020-11-01 14:56 UTC, max123kl commented on administrator/language/de-DE/com_media.ini
> +COM_MEDIA_FIELD_MAXIMUM_SIZE_DESC="Die maximale Größe zum Hochladen (in Bytes). Auf „0“ setzen für unbegrenzt.<br /><br /><strong>Hinweis:</strong><br />Die Größe wird durch eingestellte Limits des S
Ich habe mir gerade einmal [diese Datei](https://github.com/joomlagerman/team/commits/master/Konventionen/Formatierungen_Warnungen-Hilfen-Beispiele.odt) angeschaut.

Wie verbindlich sind diese Konventionen denn noch? Rot war jedenfalls falsch für "Hinweis".

2020-11-01 18:14 UTC, max123kl commented on administrator/language/de-DE/com_media.ini
> +COM_MEDIA_FIELD_MAXIMUM_SIZE_DESC="Die maximale Größe zum Hochladen (in Bytes). Auf „0“ setzen für unbegrenzt.<br /><br /><strong>Hinweis:</strong><br />Die Größe wird durch eingestellte Limits des S
@tecpromotion  @zero-24 
Wenn auf die Farbe verzichtet werden soll und die Verstärkung mit `<strong>` nicht ausreichend ist, dann könnte man auch folgendes machen:
![Invertiert](https://user-images.githubusercontent.com/853497/97810729-45574d00-1c76-11eb-9461-d26640ca62d8.png)
Im Code würde das so aussehen:
```suggestion
COM_MEDIA_FIELD_MAXIMUM_SIZE_DESC="Die maximale Größe zum Hochladen (in Bytes). Auf „0“ setzen für unbegrenzt.<br /><br /><span style="background-color:currentColor"><span style="color:white"><strong>&#8239Hinweis:&#8239</strong></span></span><br />Die Größe wird durch eingestellte Limits des Servers begrenzt."
```

2020-11-01 18:17 UTC, zero-24 commented on administrator/language/de-DE/com_media.ini
> +COM_MEDIA_FIELD_MAXIMUM_SIZE_DESC="Die maximale Größe zum Hochladen (in Bytes). Auf „0“ setzen für unbegrenzt.<br /><br /><strong>Hinweis:</strong><br />Die Größe wird durch eingestellte Limits des S
Hmm wenn ich jetzt vso drüber nachdenke sind inline styles sind nicht so gut. Besser wäre strong oder classen da diese vom csp nicht blockiert werden.

2020-11-01 18:20 UTC, max123kl commented on administrator/language/de-DE/com_media.ini
> +COM_MEDIA_FIELD_MAXIMUM_SIZE_DESC="Die maximale Größe zum Hochladen (in Bytes). Auf „0“ setzen für unbegrenzt.<br /><br /><strong>Hinweis:</strong><br />Die Größe wird durch eingestellte Limits des S
Genau das wollte ich Stefan gerade vorschlagen, hat er doch erwähnt, dass er an einem neuen Template arbeitet

2020-11-01 18:29 UTC, tecpromotion submitted a review, later dismissed

2020-11-01 18:34 UTC, max123kl commented
@tecpromotion habe ich dich richtig verstanden – nur `<strong>` verwenden?

2020-11-01 18:34 UTC, tecpromotion commented on administrator/language/de-DE/com_media.ini
> +COM_MEDIA_FIELD_MAXIMUM_SIZE_DESC="Die maximale Größe zum Hochladen (in Bytes). Auf „0“ setzen für unbegrenzt.<br /><br /><strong>Hinweis:</strong><br />Die Größe wird durch eingestellte Limits des S
Ich arbeite an keinem Template 😏
Soviel Freizeit hab ich nicht. 
Wir sollten auf jegliche Inline Styles verzichten und mit strong soweit es geht arbeiten. 
Im Hinblick auf die Barrierefreiheit ist das wohl am besten. Nicht das wir Kontraste oder Farben vorgeben die dann jemanden einschränken.

2020-11-01 18:36 UTC, tecpromotion commented
> @tecpromotion habe ich dich richtig verstanden – nur `<strong>` verwenden?

Ich meine ja. Was meinst du @zero-24 ?

2020-11-01 18:39 UTC, zero-24 commented
Ja :+1:

2020-11-01 19:36 UTC, max123kl commented
PR wäre nach Review fertig zum Mergen

2020-11-01 20:24 UTC, max123kl commented
Eine Klasse für invertierten Text gibt es im Core

![Invertiert_class](https://user-images.githubusercontent.com/853497/97813444-95d7a600-1c88-11eb-9c4a-76302323f307.png)

2020-11-01 20:31 UTC, tecpromotion requested changes
One break is missing

2020-11-01 20:31 UTC, tecpromotion commented on administrator/language/de-DE/mod_login.ini
> +MOD_LOGIN_XML_DESCRIPTION="Dieses Modul stellt ein Anmeldeformular mit Benutzername und Passwort zur Verfügung.<br /><strong>Warnung:</strong><br />Dieses Modul sollte nicht versteckt werden."
```suggestion
MOD_LOGIN_XML_DESCRIPTION="Dieses Modul stellt ein Anmeldeformular mit Benutzername und Passwort zur Verfügung.<br /><br /><strong>Warnung:</strong><br />Dieses Modul sollte nicht versteckt werden."
```

2020-11-02 05:36 UTC, tecpromotion commented on administrator/language/de-DE/plg_user_joomla.sys.ini
> +PLG_USER_JOOMLA_XML_DESCRIPTION="Steuert die Joomla!-Standard-Benutzer-Synchronisation.<br /><strong>Warnung:</strong><br />Es muss mindestens ein Plugin aktiviert sein, das die Benutzersitzungen ver
```suggestion
PLG_USER_JOOMLA_XML_DESCRIPTION="Steuert die Joomla!-Standard-Benutzer-Synchronisation.<br /><br /><strong>Warnung:</strong><br />Es muss mindestens ein Plugin aktiviert sein, das die Benutzersitzungen verwaltet, da man sonst jede Zugriffsmöglichkeit auf die Website verliert."
```

2020-11-02 05:36 UTC, tecpromotion commented on language/de-DE/mod_menu.ini
> +MOD_MENU_FIELD_TARGET_DESC="JavaScript-Positionswerte für das Pop-up-Fenster.<br /><br /><<strong>Beispiel:</strong><br />„top=50, left=50, width=200, height=300“"
```suggestion
MOD_MENU_FIELD_TARGET_DESC="JavaScript-Positionswerte für das Pop-up-Fenster.<br /><br /><strong>Beispiel:</strong><br />„top=50, left=50, width=200, height=300“"
```

2020-11-02 05:37 UTC, tecpromotion commented on language/de-DE/mod_tags_popular.ini
> +MOD_TAGS_POPULAR_FIELD_MINSIZE_DESC="Die minimale Schriftgröße für die Schlagwörter, proportional zur Standardschriftgröße der Website.<br /><strong>Beispiel:</strong><br />„2“ bedeutet 200 % der Sta
```suggestion
MOD_TAGS_POPULAR_FIELD_MINSIZE_DESC="Die minimale Schriftgröße für die Schlagwörter, proportional zur Standardschriftgröße der Website.<br /><br /><strong>Beispiel:</strong><br />„2“ bedeutet 200 % der Standardschriftgröße."
```

2020-11-02 05:38 UTC, tecpromotion commented on administrator/language/de-DE/com_banners.ini
> +COM_BANNERS_FIELD_STICKY_DESC="Sind ein oder mehrere Banner in einer Kategorie als „wichtig“ markiert, so werden diese bevorzugt behandelt.<br /><strong>Beispiel:</strong><br />Wenn zwei Banner in ei
```suggestion
COM_BANNERS_FIELD_STICKY_DESC="Sind ein oder mehrere Banner in einer Kategorie als „wichtig“ markiert, so werden diese bevorzugt behandelt.<br /><br /><strong>Beispiel:</strong><br />Wenn zwei Banner in einer Kategorie als „wichtig“ markiert werden und ein drittes nicht, so wird das dritte Banner nicht angezeigt, wenn das Modul die Einstellung „Wichtig, Zufällig“ nutzt. Es werden dann nur die beiden wichtigen Banner angezeigt."
```

2020-11-02 05:38 UTC, tecpromotion commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_FIELD_SEF_REWRITE_DESC="Auswählen, ob das Rewrite-Modul, um Webadressen abzufangen die spezifische Bedingungen erfüllen, um sie umzuschreiben, genutzt werden soll. Verfügbar für IIS 7 und
```suggestion
COM_CONFIG_FIELD_SEF_REWRITE_DESC="Auswählen, ob das Rewrite-Modul, um Webadressen abzufangen die spezifische Bedingungen erfüllen, um sie umzuschreiben, genutzt werden soll. Verfügbar für IIS 7 und Apache.<br /><strong>Nur Apache-Webserver.</strong><br /><strong>Warnung:</strong><br />Unbedingt vor der Aktivierung die Datei „htaccess<strong>.txt</strong>“ in „<strong><u>.</u></strong>htaccess“ umbenennen.<br /><strong>Nur IIS 7-Webserver.</strong><br /><br /><strong>Warnung:</strong><br />Unbedingt vor der Aktivierung und nach der Installation des IIS URL-Rewrite-Moduls, die Datei „web.config.txt“ in „web.config“ umbenennen."
```

2020-11-02 05:41 UTC, tecpromotion commented on administrator/language/de-DE/com_languages.ini
> +COM_LANGUAGES_VIEW_OVERRIDE_SEARCH_TIP="Ein String in einer Sprachdatei besteht aus zwei Teilen: Einem spezifischen Sprachschlüssel und seinem Text.<br /><br /><strong>Beispiel:</strong><br />COM_CON
```suggestion
COM_LANGUAGES_VIEW_OVERRIDE_SEARCH_TIP="Ein String in einer Sprachdatei besteht aus zwei Teilen: Einem spezifischen Sprachschlüssel und seinem Text.<br /><br /><strong>Beispiel:</strong><br />COM_CONTENT_READ_MORE=\"Read more: \"<br />„<u>COM_CONTENT_READ_MORE</u>“ ist der Sprachschlüssel und „<u>Read more: </u>“ ist der Text.<br /><br />Man muss den Namen des Sprachschlüssels beibehalten um den Text durch einen anderen zu ersetzen (override).<br />In das nachfolgende Feld nach dem Namen des Sprachschlüssels oder den zu ersetzenden Text suchen.<br />Durch Anklicken des gewünschten Ergebnisses wird automatisch der richtige Sprachschlüssel in das Formular eingesetzt."
```

2020-11-02 05:43 UTC, tecpromotion requested changes
some typos and fixes

2020-11-02 08:34 UTC, tecpromotion approved these changes
Thanks @max123kl

2020-11-02 08:35 UTC, merged