[4.0] missing language string(s) in /admin.../com_users.ini (file not in sync with core)
joomlagerman/joomla pull request #1420
Opened 2020-11-17 14:23 UTC by max123kl

add missing strings
remove obsolete strings

Pull Request für Issue #1419

### Zusammenfassung der Änderungen
2 Zeilen geändert

2020-11-17 14:30 UTC, max123kl commented
Zum Glück waren nur 2 Zeilen zu editieren (notepad++ hatte mir wesentlich mehr (false positive) Fehler angezeigt)

2020-11-17 18:31 UTC, tecpromotion commented on administrator/language/de-DE/com_users.ini
> +COM_USERS_CONFIG_FIELD_FRONTEND_RESET_TIME_LABEL="Zurücksetzungs-Zeit"
```suggestion
COM_USERS_CONFIG_FIELD_FRONTEND_RESET_TIME_LABEL="Zurücksetzungsdauer"
```
Umgangssprachlich und mehr Treffer in Google.

2020-11-17 18:31 UTC, tecpromotion requested changes
Wording

2020-11-17 18:48 UTC, tecpromotion approved these changes

2020-11-17 18:48 UTC, merged

2020-11-18 06:03 UTC, max123kl commented on administrator/language/de-DE/com_users.ini
> +COM_USERS_CONFIG_FIELD_FRONTEND_RESET_TIME_LABEL="Zurücksetzungsdauer"
Ich war mit meiner Version auch nicht voll zufrieden, aber die neue Formulierung trifft die Situation auch nicht richtig.

Es geht doch hier um die Zeitspanne, innerhalb der die Passwort-Rücksetzungen (bis zum davor definierten Maximum) gezählt werden. Das ist mMn keine "Dauer".

2020-11-18 06:22 UTC, max123kl commented on administrator/language/de-DE/com_users.ini
> +COM_USERS_CONFIG_FIELD_FRONTEND_RESET_TIME_LABEL="Zurücksetzungsdauer"
Meinen Vorschlag hatte ich aus den Übersetzungsvorschlägen aus JDOC entnommen.
![2020-11-18_071929](https://user-images.githubusercontent.com/853497/99492980-bc772b80-296e-11eb-8932-691577cda50c.png)