Update com_users.ini (bessere Wortwahl)
joomlagerman/joomla pull request #1441
Opened 2020-11-20 08:40 UTC by max123kl

### Zusammenfassung der Änderungen
vermeide doppelte Wortwahl

### Wo wird der Sprachstring angezeigt / Wie kann getestet werden
Backend

2020-11-20 08:42 UTC, tecpromotion requested changes
erhöhen hört sich sehr old school an, oder?

2020-11-20 08:42 UTC, tecpromotion commented on administrator/language/de-DE/com_users.ini
> +COM_USERS_A11Y_SETTINGS_FIELD_FONTSIZE="Schriftgröße erhöhen"
```suggestion
COM_USERS_A11Y_SETTINGS_FIELD_FONTSIZE="Schrift vergrößern"
```

ist das nicht klarer?

2020-11-20 09:28 UTC, jduerscheid commented on administrator/language/de-DE/com_users.ini
> +COM_USERS_A11Y_SETTINGS_FIELD_FONTSIZE="Schriftgröße erhöhen"
Ja finde auch dass das so klarer ist.

2020-11-20 09:43 UTC, jduerscheid commented
Frage ist dann aber auch ob man dann nicht auch aus  "Hoher Kontrast" nicht besser auch direkt "Kontrast vergrößern" Ist unverfänglicher, weil Hoher Kontrast ist in meinen Augen ein nicht genau definierter Wert.

2020-11-20 10:58 UTC, tecpromotion commented
> Frage ist dann aber auch ob man dann nicht auch aus "Hoher Kontrast" nicht besser auch direkt "Kontrast vergrößern" Ist unverfänglicher, weil Hoher Kontrast ist in meinen Augen ein nicht genau definierter Wert.

Ja, das macht in dem Kontext durchaus Sinn.

![Uploading Bildschirmfoto 2020-11-20 um 11.57.28.png…]()

2020-11-20 10:59 UTC, tecpromotion commented on administrator/language/de-DE/com_users.ini
> +COM_USERS_A11Y_SETTINGS_FIELD_FONTSIZE="Schriftgröße erhöhen"
```suggestion
COM_USERS_A11Y_SETTINGS_FIELD_FONTSIZE="Schrift vergrößern"
```

2020-11-20 10:59 UTC, tecpromotion commented on administrator/language/de-DE/com_users.ini
>  COM_USERS_A11Y_SETTINGS_FIELD_CONTRAST="Hoher Kontrast"
```suggestion
COM_USERS_A11Y_SETTINGS_FIELD_CONTRAST="Kontrast vergrößern"
```

2020-11-20 11:00 UTC, tecpromotion requested changes
passt?

2020-11-20 11:03 UTC, jduerscheid commented
Ja für mich passt das so

2020-11-20 20:12 UTC, max123kl commented on administrator/language/de-DE/com_users.ini
> +COM_USERS_A11Y_SETTINGS_FIELD_FONTSIZE="Schriftgröße erhöhen"
Ist typografisch so nicht ganz korrekt, aber damit kann ich leben

2020-11-20 20:18 UTC, max123kl commented on administrator/language/de-DE/com_users.ini
>  COM_USERS_A11Y_SETTINGS_FIELD_CONTRAST="Hoher Kontrast"
Das finde ich besser:
```suggestion
COM_USERS_A11Y_SETTINGS_FIELD_CONTRAST="Höherer Kontrast"
```
 "kleiner/großer"  vs. "geringer/hoher" Kontrast

2020-11-23 07:55 UTC, tecpromotion approved these changes
thanks @max123kl and @jduerscheid

2020-11-23 07:55 UTC, merged