[4.0] sync file administrator/com_config.ini with core file
joomlagerman/joomla pull request #1586
Opened 2021-01-30 18:21 UTC by tecpromotion

Pull Request für Issue #1585 .

### Zusammenfassung der Änderungen

file is now of the same structure as the core

### Wo wird der Sprachstring angezeigt / Wie kann getestet werden

backend

2021-01-30 18:40 UTC, tecpromotion commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_WEBSERVICES_SETTINGS="Web Services"
@zero-24 Please check this and the following lines.

2021-01-30 18:50 UTC, tecpromotion commented
@zero-24 I have made a PR in the Core for the alphabetical sorting.

https://github.com/joomla/joomla-cms/pull/32211

2021-01-30 21:39 UTC, zero-24 commented
> @zero-24 I have made a PR in the Core for the alphabetical sorting.
> 
> [joomla/joomla-cms#32211](https://github.com/joomla/joomla-cms/pull/32211)

Merged.

2021-01-30 21:54 UTC, zero-24 requested changes

2021-01-30 21:54 UTC, zero-24 commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_FIELD_DATABASE_PASSWORD_DESC="Das Passwort für den Zugriff auf die Datenbank.<br /><br /><strong>Warnung:</strong><br />Dieses Feld sollte nicht verändert werden, außer in speziellen Fälle
```suggestion
COM_CONFIG_FIELD_DATABASE_PASSWORD_DESC="Das Passwort für den Zugriff auf die Datenbank.<br /><br /><strong>Warnung:</strong><br />Dieses Feld sollte nicht verändert werden, außer in speziellen Fällen, wie z.B. beim Umzug der Datenbank zu einem neuen Webhoster."
```

Was ist `&#8239;`?

2021-01-30 21:54 UTC, zero-24 commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_FIELD_FILESYSTEM_PATH_DESC="Der Pfad des Dateisystems, in dem die Sitzungsdaten gespeichert werden.<br>Wenn leer, wird das temporäre Verzeichnis des Systems verwendet."
```suggestion
COM_CONFIG_FIELD_FILESYSTEM_PATH_DESC="Der Pfad des Dateisystems, in dem die Sitzungsdaten gespeichert werden.<br>Wenn dieses Feld leer bleibt, wird das temporäre Verzeichnis des Systems verwendet."
```

2021-01-30 21:54 UTC, zero-24 commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_FIELD_REDIS_PERSISTENT_LABEL="Dauerhafter Redis"
```suggestion
COM_CONFIG_FIELD_REDIS_PERSISTENT_LABEL="Persistentes Redis"
```

2021-01-30 21:54 UTC, zero-24 commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_SENDMAIL_BODY="Dies ist eine Test-E-Mail via \"{METHOD}\". Bei Erhalt dieser E-Mail, sind die E-Mail-Einstellungen korrekt."
```suggestion
COM_CONFIG_SENDMAIL_BODY="Dies ist eine Test-E-Mail via \"{METHOD}\". Der Erhalt dieser E-Mail bestätigt das die E-Mail-Einstellungen korrekt sind."
```

2021-01-30 21:54 UTC, zero-24 commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_FIELD_WEBSERVICES_CORS_ALLOW_HEADERS_DESC="Gibt die Header (Kopfzeilen) an, die als Antwort auf eine Preflight-Anfrage zurückgesendet werden. Standard: Content-Type,X-Joomla-Token"
```suggestion
COM_CONFIG_FIELD_WEBSERVICES_CORS_ALLOW_HEADERS_DESC="Gibt die Header an, die als Antwort auf eine Preflight-Anfrage zurückgesendet werden. Standard: Content-Type,X-Joomla-Token"
```

2021-01-30 21:54 UTC, zero-24 commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_FIELD_WEBSERVICES_CORS_ALLOW_ORIGIN_DESC="Gibt die Origin (Herkunft) an, die auf Web Services auf dieser Website zugreifen darf, die als Antwort auf eine Preflight-Anfrage zurückgeschickt
```suggestion
COM_CONFIG_FIELD_WEBSERVICES_CORS_ALLOW_ORIGIN_DESC="Gibt die Origins an, welche auf die Web Services dieser Website zugreifen dürfen. Standardwert: „*“ d.h. es gibt keine Einschränkungen."
```

2021-01-30 21:54 UTC, zero-24 commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_FIELD_WEBSERVICES_CORS_ALLOW_METHODS_DESC="Gibt die Web Service-Methode(n) an, auf die auf dieser Website zugegriffen werden darf und die als Antwort auf eine Preflight-Anfrage zurückgesch
```suggestion
COM_CONFIG_FIELD_WEBSERVICES_CORS_ALLOW_METHODS_DESC="Gibt die Web Service-Methode(n) an, auf die  zugegriffen werden darf. Standardwert: Alle für die angeforderte Route verfügbaren Methoden."
```

2021-01-30 22:17 UTC, max123kl commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_FIELD_DATABASE_PASSWORD_DESC="Das Passwort für den Zugriff auf die Datenbank.<br /><br /><strong>Warnung:</strong><br />Dieses Feld sollte nicht verändert werden, außer in speziellen Fälle
> Was ist `&#8239;`?

Das soll wohl einen eingefügten, minimalen Leerraum darstellen, der öfter diskutiert wird.

Wobei ich persönlich des "z.B." ohne Zwischenraum bevorzuge.
Siehe auch den Abschnitt ["Leerzeichen"](https://www.key-shortcut.com/html-entities/eur-typographie)

2021-01-30 23:09 UTC, tecpromotion commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_FIELD_DATABASE_PASSWORD_DESC="Das Passwort für den Zugriff auf die Datenbank.<br /><br /><strong>Warnung:</strong><br />Dieses Feld sollte nicht verändert werden, außer in speziellen Fälle
Haben wir ein paar Mal drin. Würde das erstmal lassen.

2021-01-30 23:12 UTC, tecpromotion commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_SENDMAIL_BODY="Dies ist eine Test-E-Mail via \"{METHOD}\". Bei Erhalt dieser E-Mail, sind die E-Mail-Einstellungen korrekt."
```suggestion
COM_CONFIG_SENDMAIL_BODY="Dies ist eine Test-E-Mail via \"{METHOD}\". Der Erhalt dieser E-Mail bestätigt, dass die E-Mail-Einstellungen korrekt sind."
```

2021-01-30 23:15 UTC, tecpromotion commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_FIELD_WEBSERVICES_CORS_ALLOW_ORIGIN_DESC="Gibt die Origin (Herkunft) an, die auf Web Services auf dieser Website zugreifen darf, die als Antwort auf eine Preflight-Anfrage zurückgeschickt
```suggestion
COM_CONFIG_FIELD_WEBSERVICES_CORS_ALLOW_ORIGIN_DESC="Gibt die Origins an, welche auf die Web Services dieser Website zugreifen dürfen. Standard: * (keine Einschränkungen)"
```

2021-01-30 23:17 UTC, tecpromotion commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_FIELD_WEBSERVICES_CORS_ALLOW_METHODS_DESC="Gibt die Web Service-Methode(n) an, auf die auf dieser Website zugegriffen werden darf und die als Antwort auf eine Preflight-Anfrage zurückgesch
```suggestion
COM_CONFIG_FIELD_WEBSERVICES_CORS_ALLOW_METHODS_DESC="Gibt die Web Service-Methode(n) an, auf die zugegriffen werden darf. Standard: Alle für die angeforderte Route verfügbaren Methoden."
```

2021-01-30 23:21 UTC, max123kl commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_FIELD_DATABASE_PASSWORD_DESC="Das Passwort für den Zugriff auf die Datenbank.<br /><br /><strong>Warnung:</strong><br />Dieses Feld sollte nicht verändert werden, außer in speziellen Fälle
Einverstanden, falls immer das "schmale Leerzeichen" verwendet wird. Das ist schließlich die typografisch richtige Schreibweise. Andererseits ist die Darstellungsqualität auf Monitoren so viel schlechter (im Gegensatz zum gedruckten Buch), sodass der "Fehler" eines fehlenden Leerzeichens aus optischen Gründen zu verschmerzen wäre.

2021-01-30 23:21 UTC, tecpromotion commented
Standardwert finde ich hier nicht so passend.

2021-01-31 10:44 UTC, zero-24 commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_FIELD_WEBSERVICES_CORSOFFF_LABEL="CORS aktivieren"
Ggf "CORS" auf https://developer.mozilla.org/de/docs/Web/HTTP/CORS verlinken?

2021-01-31 11:27 UTC, tecpromotion commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_FIELD_WEBSERVICES_CORSOFFF_LABEL="CORS aktivieren"
```suggestion
COM_CONFIG_FIELD_WEBSERVICES_CORSOFFF_LABEL="<a href='https://developer.mozilla.org/de/docs/Web/HTTP/CORS' target='_blank' rel='noopener noreferrer'>CORS</a> aktivieren"
```

2021-01-31 11:47 UTC, zero-24 approved these changes

2021-01-31 11:47 UTC, merged

2021-01-31 11:48 UTC, zero-24 commented
Merged