[4.0] Com_fields
joomlagerman/joomla pull request #1631
Opened 2021-03-18 20:51 UTC by chmst

Pull Request für Issue #1627 .

### Zusammenfassung der Änderungen
Sprachdatei com_fields abgeglichen mit 40. dev. , alphaordering

2021-03-18 21:16 UTC, tecpromotion commented on administrator/language/de-DE/com_fields.ini
> +COM_FIELDS_FIELD_CLASS_LABEL="Feldklasse (CSS)"
```suggestion
COM_FIELDS_FIELD_CLASS_LABEL="CSS-Klasse Feld"
```

2021-03-18 21:20 UTC, tecpromotion commented on administrator/language/de-DE/com_fields.ini
> +COM_FIELDS_FIELD_CLASS_DESC="The class attributes of the field in the edit form. If multiple classes are needed, list them with spaces."
```suggestion
COM_FIELDS_FIELD_CLASS_DESC="Die Klassenattribute des Feldes im Bearbeitungsformular. Mehrere Klassen mit Leerzeichen getrennt aufführen."
```

Bearbeitungsformular ist noch unstimmig da bisher nie genutzt.

2021-03-18 21:22 UTC, tecpromotion commented on administrator/language/de-DE/com_fields.ini
> +COM_FIELDS_FIELD_LABEL_RENDER_CLASS_LABEL="CSS-Klasse Feld (Ausgabe)"
```suggestion
COM_FIELDS_FIELD_LABEL_RENDER_CLASS_LABEL="CSS-Klasse Label"
```

2021-03-18 21:25 UTC, tecpromotion commented on administrator/language/de-DE/com_fields.ini
> +COM_FIELDS_FIELD_CLASS_DESC="The class attributes of the field in the edit form. If multiple classes are needed, list them with spaces."
```suggestion
COM_FIELDS_FIELD_CLASS_DESC="Das CSS-Klassenattribut für das Feld, wenn es bearbeitet wird. Mehrere Klassen mit Leerzeichen trennen."
```

2021-03-18 21:29 UTC, tecpromotion commented on administrator/language/de-DE/com_fields.ini
> +COM_FIELDS_FIELDS_FILTER_SEARCH_DESC="In Titel und Notiz suchen. Als Präfix „ID:“ verwenden, um nach einer Feld-ID zu suchen."
```suggestion
COM_FIELDS_FIELDS_FILTER_SEARCH_DESC="Suche in Feldname, Titel oder Notiz. ID: verwenden um eine Feld-ID zu suchen. AUTHOR: verwenden um nach Feld-Autor zu suchen."
```

2021-03-18 21:32 UTC, tecpromotion commented on administrator/language/de-DE/com_fields.ini
> +COM_FIELDS_GROUP_SAVE_SUCCESS="Die Feldgruppe wurde gespeichert"
```suggestion
COM_FIELDS_GROUP_SAVE_SUCCESS="Feldgruppe gespeichert"
```

2021-03-18 21:35 UTC, tecpromotion commented on administrator/language/de-DE/com_fields.ini
> +COM_FIELDS_GROUPS_FILTER_SEARCH_DESC="Suche inerhalb der Feldbezeichnung. Mit einem vorangestellten ID: kann nach der ID gesucht werden."
```suggestion
COM_FIELDS_GROUPS_FILTER_SEARCH_DESC="Suche in Feldgruppen Titel. ID: verwenden um nach Feldgruppen-ID zu suchen."
```

2021-03-18 21:36 UTC, tecpromotion commented on administrator/language/de-DE/com_fields.ini
> +COM_FIELDS_GROUPS_FILTER_SEARCH_LABEL="Search Field Groups"
```suggestion
COM_FIELDS_GROUPS_FILTER_SEARCH_LABEL="Feldgruppe suchen"
```

2021-03-18 21:38 UTC, tecpromotion requested changes
Ein paar Vorschläge. Hauptsächlich um das Wording einheitlich zu halten zu anderen Übersetzungen.

2021-03-19 13:54 UTC, chmst commented on administrator/language/de-DE/com_fields.ini
> +COM_FIELDS_FIELDS_FILTER_SEARCH_DESC="In Titel und Notiz suchen. Als Präfix „ID:“ verwenden, um nach einer Feld-ID zu suchen."
Es gibt nur Titel. Feldname wäre schöner, aber dann muss alles überarbeitet werden

2021-03-19 14:04 UTC, tecpromotion commented on administrator/language/de-DE/com_fields.ini
> +COM_FIELDS_FIELDS_FILTER_SEARCH_DESC="In Titel und Notiz suchen. Als Präfix „ID:“ verwenden, um nach einer Feld-ID zu suchen."
? https://github.com/joomla/joomla-cms/blob/09537dd8a9ad64ff289bf0ec8a62e55a3b108764/administrator/language/en-GB/com_fields.ini#L62

2021-03-19 14:15 UTC, chmst commented on administrator/language/de-DE/com_fields.ini
> +COM_FIELDS_FIELDS_FILTER_SEARCH_DESC="In Titel und Notiz suchen. Als Präfix „ID:“ verwenden, um nach einer Feld-ID zu suchen."
falsch ist falsch ... 
![grafik](https://user-images.githubusercontent.com/1035262/111793873-faa53d00-88c5-11eb-8ca6-f8a5a738d5b8.png)

2021-03-19 14:22 UTC, chmst commented on administrator/language/de-DE/com_fields.ini
> +COM_FIELDS_FIELD_LABEL_RENDER_CLASS_LABEL="CSS-Klasse Feld (Ausgabe)"
Label heisst Bexhriftung, das passt besser.

2021-03-19 14:49 UTC, chmst commented on administrator/language/de-DE/com_fields.ini
> +COM_FIELDS_FIELDS_FILTER_SEARCH_DESC="In Titel und Notiz suchen. Als Präfix „ID:“ verwenden, um nach einer Feld-ID zu suchen."
Der englische text ist falsch. Es gibt auch keinen Autor bei den Feldern. 
Die Frage ist: Das Falsche übersetzen und einen PR für englisch machen und dann wieder hier korrigieren oder gleich auf deutsch richtig schreiben?

2021-03-19 14:51 UTC, chmst commented on administrator/language/de-DE/com_fields.ini
> +COM_FIELDS_FIELD_CLASS_LABEL="Feldklasse (CSS)"
erledigt

2021-03-19 14:51 UTC, tecpromotion commented
Ich schaue zeitnah mal rein.

2021-03-19 14:52 UTC, chmst commented on administrator/language/de-DE/com_fields.ini
> +COM_FIELDS_FIELDS_FILTER_SEARCH_DESC="In Titel und Notiz suchen. Als Präfix „ID:“ verwenden, um nach einer Feld-ID zu suchen."
commited - bitte nochmal drüberschauen

2021-03-19 14:55 UTC, chmst commented
Ich mach einen PR für englisch wegen des search.

2021-03-20 11:58 UTC, tecpromotion approved these changes
many thanks @chmst

2021-03-20 11:59 UTC, merged