[4.0] Remove com_admin profile view
joomlagerman/joomla pull request #1753
Opened 2021-05-19 11:13 UTC by max123kl

Pull Request für Issue #1654

### Zusammenfassung der Änderungen
a) Überzählige Strings gelöscht
b) Fehlende Strings (Vergleich zur Core-Datei) eingefügt
c) Übersetzung der neuen Strings

### Wo wird der Sprachstring angezeigt / Wie kann getestet werden
Backend

### Bitte überprüfen
in Zeile 141 werden im String 2 Backslashes `\` (zur Formatierung?) verwendet
Ist die Anwendung richtig – ist im Core ev. ein Typo?

2021-05-19 11:14 UTC, max123kl commented on administrator/language/de-DE/com_admin.ini
> +COM_ADMIN_POSTINSTALL_MSG_BEHIND_LOAD_BALANCER_TITLE="Neue Server-Einstellung \„Hinter einem Load-Balancer“\"
Typo?

2021-05-29 07:48 UTC, tecpromotion commented on administrator/language/de-DE/com_admin.ini
> +COM_ADMIN_POSTINSTALL_MSG_BEHIND_LOAD_BALANCER_ACTION="Aktivieren von Einstellungen hinter Load-Balancern"
```suggestion
COM_ADMIN_POSTINSTALL_MSG_BEHIND_LOAD_BALANCER_ACTION="Einstellung „Load Balancer aktivieren“"
```

2021-05-29 07:49 UTC, tecpromotion commented on administrator/language/de-DE/com_admin.ini
> +COM_ADMIN_POSTINSTALL_MSG_BEHIND_LOAD_BALANCER_DESCRIPTION="<p>Für Joomla-Seiten, die hinter Load-Balancern und Reverse-Proxies gehostet werden, wurde mit Joomla 3.9.26 eine neue globale Konfiguratio
```suggestion
COM_ADMIN_POSTINSTALL_MSG_BEHIND_LOAD_BALANCER_DESCRIPTION="<p>Für Joomla-Seiten, die hinter Load Balancern und Reverse Proxies gehostet werden, wurde mit Joomla 3.9.26 eine neue globale Konfigurationseinstellung eingeführt.</p><p>Diese Einstellung, wenn sie aktiviert ist, erlaubt es dem Load Balancer/Reverse Proxy, die echte IP-Adresse der Besucher zu liefern. Diese IP wird dann in den Aktivitätsprotokollen verwendet und für die Verfolgung von Abstimmungen über Artikel genutzt (wenn diese Funktionen aktiviert sind).</p><p><strong>Diese Funktion sollte ausschließlich für Websites hinter einem Load Balancer/Reverse Proxy aktiviert werden.</strong></p>"
```

2021-05-29 07:49 UTC, tecpromotion commented on administrator/language/de-DE/com_admin.ini
> +COM_ADMIN_POSTINSTALL_MSG_BEHIND_LOAD_BALANCER_TITLE="Neue Server-Einstellung \„Hinter einem Load-Balancer“\"
```suggestion
COM_ADMIN_POSTINSTALL_MSG_BEHIND_LOAD_BALANCER_TITLE="Neue Konfigurationseinstellung „Load Balancer aktivieren“"
```

2021-05-29 07:51 UTC, tecpromotion commented on administrator/language/de-DE/com_admin.ini
> +COM_ADMIN_POSTINSTALL_MSG_HTACCESS_AUTOINDEX_DESCRIPTION="<p>Vor der Version 3.9.22 enthielt die vorgegebene Datei htaccess.txt fehlerhaften Code, der zum Deaktivieren von Verzeichnisauflistungen ged
```suggestion
COM_ADMIN_POSTINSTALL_MSG_HTACCESS_AUTOINDEX_DESCRIPTION="<p>Vor 3.9.22 enthielt die Standarddatei <strong>htaccess.txt</strong> fehlerhaften Code zum Deaktivieren von Verzeichnisauflistungen. Das Sicherheitsteam empfiehlt, die notwendigen Änderungen manuell auf jede bestehende .htaccess-Datei anzuwenden, da diese Datei nicht automatisch aktualisiert werden kann.</p><p>Alter Code:</p><pre>&lt;IfModule autoindex&gt;\n  IndexIgnore *\n&lt;/IfModule&gt;</pre><p>Neuer Code:</p><pre>&lt;IfModule mod_autoindex.c&gt;\n  IndexIgnore *\n&lt;/IfModule&gt;</pre>"
```

2021-05-29 07:51 UTC, tecpromotion commented on administrator/language/de-DE/com_admin.ini
> +COM_ADMIN_POSTINSTALL_MSG_HTACCESS_AUTOINDEX_TITLE=".htaccess-Update wegen der Verzeichnislisten"
```suggestion
COM_ADMIN_POSTINSTALL_MSG_HTACCESS_AUTOINDEX_TITLE=".htaccess Aktualisierung in Bezug auf Verzeichniseinträge"
```

2021-05-29 08:00 UTC, tecpromotion commented on administrator/language/de-DE/com_admin.ini
> +COM_ADMIN_A11Y_SETTINGS_FIELD_CONTRAST="High Contrast"
```suggestion
COM_ADMIN_A11Y_SETTINGS_FIELD_CONTRAST="Höherer Kontrast"
```

2021-05-29 08:00 UTC, tecpromotion commented on administrator/language/de-DE/com_admin.ini
> +COM_ADMIN_A11Y_SETTINGS_FIELD_FONTSIZE="Increase Font Size"
```suggestion
COM_ADMIN_A11Y_SETTINGS_FIELD_FONTSIZE="Schrift vergrößern"
```

2021-05-29 08:01 UTC, tecpromotion commented on administrator/language/de-DE/com_admin.ini
> +COM_ADMIN_A11Y_SETTINGS_FIELD_HIGHLIGHT="Highlight Links"
```suggestion
COM_ADMIN_A11Y_SETTINGS_FIELD_HIGHLIGHT="Links hervorheben"
```

2021-05-29 08:01 UTC, tecpromotion commented on administrator/language/de-DE/com_admin.ini
> +COM_ADMIN_A11Y_SETTINGS_FIELD_MONOCHROME="Monochrome"
```suggestion
COM_ADMIN_A11Y_SETTINGS_FIELD_MONOCHROME="Monochrom"
```

2021-05-29 08:01 UTC, tecpromotion commented on administrator/language/de-DE/com_admin.ini
> +COM_ADMIN_A11Y_SETTINGS_FIELDSET_LABEL="Accessibility Settings"
```suggestion
COM_ADMIN_A11Y_SETTINGS_FIELDSET_LABEL="Einstellungen zur Barrierefreiheit"
```

2021-05-29 08:09 UTC, tecpromotion requested changes
@max123kl Zeile 28 bitte mal prüfen.

2021-05-29 08:09 UTC, tecpromotion commented on administrator/language/de-DE/com_admin.ini
> +COM_ADMIN_EXTENSION_AVAILABLE="Available"
```suggestion
COM_ADMIN_EXTENSION_AVAILABLE="Verfügbar"
```
Passt das an der Stelle?

2021-05-29 08:23 UTC, tecpromotion approved these changes

2021-05-29 08:23 UTC, merged