[4.0] globale Konfiguration_Kontakte_Formular
joomlagerman/joomla pull request #1789
Opened 2021-05-29 08:40 UTC by max123kl

Pull Request für Issue #1786

### Zusammenfassung der Änderungen
COM_CONTACT_FIELD_CAPTCHA_LABEL="<a href=\"https://de.wikipedia.org/wiki/CAPTCHA\" target=\"_blank\" rel=\"noopener noreferrer\">Captcha</a> für Kontakte aktivieren"
in `administrator/language/de-DE/com_contact.ini`

### Wo wird der Sprachstring angezeigt / Wie kann getestet werden

2021-05-29 12:13 UTC, tecpromotion requested changes
Schließedes a-TAG fehlt.

2021-05-29 12:14 UTC, tecpromotion commented on administrator/language/de-DE/com_contact.ini
> +COM_CONTACT_FIELD_CAPTCHA_LABEL="<a href="https://de.wikipedia.org/wiki/CAPTCHA\" target="_blank" rel="noopener noreferrer">Captcha für Kontakte aktivieren"
```suggestion
COM_CONTACT_FIELD_CAPTCHA_LABEL="<a href=\"https://de.wikipedia.org/wiki/CAPTCHA\" target=\"_blank\" rel=\"noopener noreferrer\">Captcha</a> für Kontakte aktivieren"
```

2021-05-29 12:15 UTC, tecpromotion commented on administrator/language/de-DE/com_contact.ini
> +COM_CONTACT_FIELD_CAPTCHA_LABEL="<a href="https://de.wikipedia.org/wiki/CAPTCHA\" target="_blank" rel="noopener noreferrer">Captcha für Kontakte aktivieren"
**\**-Zeichen fehlten. Das würde zu einem kaputten String führen und alles danach würde nicht mehr geladen werden können.

2021-05-29 12:27 UTC, max123kl commented on administrator/language/de-DE/com_contact.ini
> +COM_CONTACT_FIELD_CAPTCHA_LABEL="<a href="https://de.wikipedia.org/wiki/CAPTCHA\" target="_blank" rel="noopener noreferrer">Captcha für Kontakte aktivieren"
Sorry, ich hatte von der falschen Quelle Copy&Paste gemacht

2021-05-31 17:45 UTC, tecpromotion reviewed
@max123kl Ich hab mir das jetzt im Backend angesehen und da man an dieser Stelle nur eine Auswahl trifft und keine Aktivierung vornimmt, habe ich den PR geschlossen.

2021-05-31 17:45 UTC, closed without merging