[4.0] mod_popular with disabled hits – part3 (last)
joomlagerman/joomla pull request #1851
Opened 2021-06-05 08:30 UTC by max123kl

Pull Request für Issue #1793

### Zusammenfassung der Änderungen
`language/.../joomla.ini` Datei an Core angepasst
enthält auch Anpassungen aus Issue #1745

### Wo wird der Sprachstring angezeigt / Wie kann getestet werden
Frontend

2021-06-05 08:43 UTC, max123kl commented
Um die noch nicht gemergten Änderungen aus PR #1846 in dem neuen Branch (Issue-1793-part3) lokal berücksichtigen zu können erscheinen hier die Commits 71a8e37, 36709e4, 936ae9f noch einmal und können vernachlässigt werden

2021-06-05 12:06 UTC, tecpromotion commented
> Um die noch nicht gemergten Änderungen aus PR #1846 in dem neuen Branch (Issue-1793-part3) lokal berücksichtigen zu können erscheinen hier die Commits 71a8e37, 36709e4, 936ae9f noch einmal und sollten nicht in diesen PR einfließen.
> 
> Ich bitte um einen Tipp

Sobald Part 2 gemerged wurde, passt es ja.

2021-06-06 13:55 UTC, tecpromotion requested changes
@max123kl merge bitte mal den aktuellen 4.0-dev Branch in diesen PR und prüf was sich ggf dann aufgelöst hat.
Danke.

2021-06-06 14:04 UTC, max123kl commented
hat ohne Konflikte gemergt

2021-06-06 14:05 UTC, tecpromotion commented on language/de-DE/joomla.ini
> +JGLOBAL_PREVIEW_POSITION="<span>Position:&nbsp;</span>%s"
```suggestion
JGLOBAL_PREVIEW_POSITION="<span>Position:</span> %s"
```

2021-06-06 14:06 UTC, tecpromotion commented on language/de-DE/joomla.ini
> +JGLOBAL_PREVIEW_STYLE="<span>Style:&nbsp;</span>%s"
```suggestion
JGLOBAL_PREVIEW_STYLE="<span>Style:</span> %s"
```

2021-06-06 14:06 UTC, tecpromotion approved these changes
thanks @max123kl

2021-06-06 14:07 UTC, max123kl commented on language/de-DE/joomla.ini
> +JGLOBAL_PREVIEW_POSITION="<span>Position:&nbsp;</span>%s"
Ich hätte zuerst von origin holen sollen und dann von upstream, sorry

2021-06-06 14:09 UTC, tecpromotion approved these changes

2021-06-06 14:09 UTC, merged