[4.0] admin container menu
joomlagerman/joomla pull request #1948
Opened 2021-07-05 05:30 UTC by max123kl

Pull Request für Issue #1945

### Zusammenfassung der Änderungen

Übersetzung aktualisiert

### Wo wird der Sprachstring angezeigt / Wie kann getestet werden
Backend

2021-07-06 04:14 UTC, tecpromotion commented on administrator/language/de-DE/com_menus.ini
> +COM_MENUS_ITEM_FIELD_COMPONENTS_CONTAINER_HIDE_ITEMS_DESC="Die Menüeinträge auswählen, die in diesem Container angezeigt oder versteckt werden sollen. Wenn es keine Menueinträge die angezeigt werden
```suggestion
COM_MENUS_ITEM_FIELD_COMPONENTS_CONTAINER_HIDE_ITEMS_DESC="Die Menüeinträge auswählen, die in diesem Container angezeigt oder versteckt werden sollen. Wenn es keine Menueinträge gibt, die angezeigt werden sollen, dann wird dieser Container ausgeblendet.<br />Bei der Installation einer neuen Komponente wird diese standardmäßig angezeigt, bis diese hier explizit versteckt wird."
```

2021-07-06 04:15 UTC, tecpromotion requested changes
Worauf bezieht sich "diese" im letzten Satz? Auf "den" Container?

2021-07-06 07:53 UTC, max123kl commented on administrator/language/de-DE/com_menus.ini
> +COM_MENUS_ITEM_FIELD_COMPONENTS_CONTAINER_HIDE_ITEMS_DESC="Die Menüeinträge auswählen, die in diesem Container angezeigt oder versteckt werden sollen. Wenn es keine Menueinträge gibt, die angezeigt w
```suggestion
COM_MENUS_ITEM_FIELD_COMPONENTS_CONTAINER_HIDE_ITEMS_DESC="Die Menüeinträge auswählen, die in diesem Container angezeigt oder versteckt werden sollen. Wenn es keine Menueinträge gibt, die angezeigt werden sollen, dann wird dieser Container ausgeblendet.<br />Bei der Installation einer neuen Komponente wird diese standardmäßig angezeigt, bis sie hier explizit versteckt wird."
```

Nachdem ich den englischen Text noch einmal gelesen habe, bin ich der Meinung, dass sich das letzte "diese" auf die Komponente bezieht. Man könnte mein eingefügtes "sie" auch durch "die Komponente" ersetzen, um die "Undeutlichkeit" zu beseitigen.

2021-07-12 18:02 UTC, tecpromotion commented on administrator/language/de-DE/com_menus.ini
> +COM_MENUS_ITEM_FIELD_COMPONENTS_CONTAINER_HIDE_ITEMS_DESC="Die Menüeinträge auswählen, die in diesem Container angezeigt oder versteckt werden sollen. Wenn es keine Menueinträge gibt, die angezeigt w
```suggestion
COM_MENUS_ITEM_FIELD_COMPONENTS_CONTAINER_HIDE_ITEMS_DESC="Die Menüeinträge auswählen, die in diesem Container angezeigt oder versteckt werden sollen. Wenn es keine Menueinträge gibt, die angezeigt werden sollen, dann wird dieser Container ausgeblendet.<br />Bei der Installation einer neuen Komponente wird diese standardmäßig angezeigt, bis die Komponente hier explizit versteckt wird."
```

2021-07-12 18:02 UTC, tecpromotion approved these changes

2021-07-12 18:03 UTC, merged