Add untranslated strings reported in crowdin
joomlagerman/joomla pull request #2020
Opened 2021-08-10 22:37 UTC by zero-24

Pull Request für Issue # .

### Zusammenfassung der Änderungen

Add untranslated strings reported in crowdin it seems some strings where changen inbetween we didnt automated the reporting to us.

### Wo wird der Sprachstring angezeigt / Wie kann getestet werden

Backend

2021-08-11 04:05 UTC, blueforce requested changes
Im String COM_CONFIG_ERROR_CUSTOM_LOG_PATH_NOTWRITABLE_USING_DEFAULT:
«...- Verwenden Sie stattdessen den Standardordner %2$s.»

besser wäre:
«...- Bitte den Standardordner %2$s verwenden.»

Begründung:
Formneutrale Ansprache ohne «Sie»...

2021-08-11 05:37 UTC, zero-24 commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_ERROR_CUSTOM_LOG_PATH_NOTWRITABLE_USING_DEFAULT="Der Ordner %1$s ist nicht beschreibbar und kann nicht für den Protokollordner verwendet werden. Verwenden Sie stattdessen den Standardordne
```suggestion
COM_CONFIG_ERROR_CUSTOM_LOG_PATH_NOTWRITABLE_USING_DEFAULT="Der Ordner %1$s ist nicht beschreibbar und kann nicht für den Protokollordner verwendet werden. Bitte den Standardordner %2$s verwenden."
```

2021-08-11 05:38 UTC, zero-24 commented
Fixed https://github.com/joomlagerman/joomla/pull/2020/commits/c68a85e64a4973fee70e5248bd7dc7d1b5d8d113 Danke @blueforce

2021-08-11 05:49 UTC, blueforce submitted a review, later dismissed

2021-08-11 19:33 UTC, tecpromotion commented on administrator/language/de-DE/com_config.ini
>  COM_CONFIG_ERROR_CUSTOM_SESSION_FILESYSTEM_PATH_NOTWRITABLE_USING_DEFAULT="The folder at %s is not writable and cannot be used to store session data, the default PHP path will be used instead."
Translation missing.

2021-08-11 19:35 UTC, tecpromotion commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_ERROR_CUSTOM_LOG_PATH_NOTWRITABLE_USING_DEFAULT="Der Ordner %1$s ist nicht beschreibbar und kann nicht für den Protokollordner verwendet werden. Bitte den Standardordner %2$s verwenden."
```suggestion
COM_CONFIG_ERROR_CUSTOM_LOG_PATH_NOTWRITABLE_USING_DEFAULT="Das Verezeichnis %1$s ist schreibgeschützt und kann nicht als Protokollvrezeichnis verwendet werden. Es wird stattdessen das Standardverzeichnis „%2$s“ verwendet."
```

See previous translations

2021-08-11 19:36 UTC, tecpromotion commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_ERROR_CUSTOM_TEMP_PATH_NOTWRITABLE_USING_DEFAULT="Der Ordner %1$s ist nicht beschreibbar und kann nicht für den temporären Ordner verwendet werden, stattdessen wird der Standardordner %2$s
```suggestion
COM_CONFIG_ERROR_CUSTOM_TEMP_PATH_NOTWRITABLE_USING_DEFAULT="Das Verzeichnis %1$s ist schreibgeschützt und kann nicht als temporäres Verzeichnis verwendet werden. Es wird stattdessen das Standardverzeichnis „%2$s“ verwendet."
```

See previous translations

2021-08-11 19:37 UTC, tecpromotion commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_ERROR_LOG_PATH_NOTWRITABLE="Der Log-Ordner ist nicht beschreibbar: %s"
```suggestion
COM_CONFIG_ERROR_LOG_PATH_NOTWRITABLE="Das Protokollverzeichnis ist schreibgeschützt: %s"
```

2021-08-11 19:38 UTC, tecpromotion commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_ERROR_TMP_PATH_NOTWRITABLE="Der temporäre Ordner ist nicht beschreibbar: %s"
```suggestion
COM_CONFIG_ERROR_TMP_PATH_NOTWRITABLE="Das temporäre Verzeichnis ist schreibgeschützt: %s"
```

2021-08-11 19:38 UTC, tecpromotion commented on administrator/language/de-DE/com_installer.sys.ini
> +COM_INSTALLER_UPDATE_VIEW_DEFAULT_TITLE="Erweiterungen aktualiesieren"
```suggestion
COM_INSTALLER_UPDATE_VIEW_DEFAULT_TITLE="Erweiterungen aktualisieren"
```

2021-08-11 19:39 UTC, tecpromotion commented on administrator/language/de-DE/com_joomlaupdate.ini
> +COM_JOOMLAUPDATE_CAPTIVE_HEADLINE="Bestätigen Sie Ihre Anmeldedaten"
```suggestion
COM_JOOMLAUPDATE_CAPTIVE_HEADLINE="Anmeldedaten bestätigen"
```

2021-08-11 19:39 UTC, tecpromotion commented on administrator/language/de-DE/com_languages.ini
> +COM_LANGUAGES_ERR_PUBLISH="Wählen Sie eine Sprache zur Veröffentlichung aus."
```suggestion
COM_LANGUAGES_ERR_PUBLISH="Eine Sprache zur Veröffentlichung auswählen."
```

2021-08-11 19:40 UTC, tecpromotion commented on administrator/language/de-DE/com_media.ini
> +COM_MEDIA_FIELD_RESTRICT_UPLOADS_EXTENSIONS_DESC="Schränken Sie das Hochladen von Dateien für Benutzer, die keine Manager sind, auf die Dateien in der Liste ein."
neutrale Sprache verwenden

2021-08-11 19:41 UTC, tecpromotion commented on administrator/language/de-DE/plg_actionlog_joomla.ini
> +PLG_ACTIONLOG_JOOMLA_API="Benutzer <a href='{accountlink}'>{username}</a> performed a {verb} on {url}"
translation missing

2021-08-11 19:41 UTC, tecpromotion commented on administrator/language/de-DE/plg_fields_usergrouplist.ini
> +PLG_FIELDS_USERGROUPLIST_DEFAULT_VALUE_DESC="Eine Komma getrennte Liste von Benutzergruppenids."
```suggestion
PLG_FIELDS_USERGROUPLIST_DEFAULT_VALUE_DESC="Eine Komma getrennte Liste von Benutzergruppen-IDs."
```

2021-08-11 19:42 UTC, tecpromotion commented on administrator/language/de-DE/plg_system_webauthn.ini
> +PLG_SYSTEM_WEBAUTHN_CANNOT_ADD_FOR_A_USER="Sie können keine Authentifikatoren im Namen von Benutzern hinzufügen oder entfernen. Die Benutzer müssen sich anmelden und ihre eigenen Geräte einrichten."
Neutrale Sprache

2021-08-11 19:43 UTC, tecpromotion requested changes
paar Anpassungen sind notwendig

2021-08-12 04:09 UTC, zero-24 commented on administrator/language/de-DE/com_media.ini
> +COM_MEDIA_FIELD_RESTRICT_UPLOADS_EXTENSIONS_DESC="Schränken Sie das Hochladen von Dateien für Benutzer, die keine Manager sind, auf die Dateien in der Liste ein."
```suggestion
COM_MEDIA_FIELD_RESTRICT_UPLOADS_EXTENSIONS_DESC="Hier kann das Hochladen für Benutzerebenen niedriger als „Manager“ auf die Dateien in der Liste sind eingeschränkt werden."
```

2021-08-12 04:11 UTC, zero-24 commented on administrator/language/de-DE/plg_actionlog_joomla.ini
> +PLG_ACTIONLOG_JOOMLA_API="Benutzer <a href='{accountlink}'>{username}</a> performed a {verb} on {url}"
```suggestion
PLG_ACTIONLOG_JOOMLA_API="Der Benutzer <a href='{accountlink}'>{username}</a> hat {verb} über {url} ausgeführt"
``

2021-08-12 04:12 UTC, zero-24 commented on administrator/language/de-DE/plg_system_webauthn.ini
> +PLG_SYSTEM_WEBAUTHN_CANNOT_ADD_FOR_A_USER="Sie können keine Authentifikatoren im Namen von Benutzern hinzufügen oder entfernen. Die Benutzer müssen sich anmelden und ihre eigenen Geräte einrichten."
```suggestion
PLG_SYSTEM_WEBAUTHN_CANNOT_ADD_FOR_A_USER="Es können keine Authentifikatoren im Namen von anderen Benutzern hinzugefügt oder entfernt werden. Die Benutzer müssen sich anmelden und ihre eigenen Geräte einrichten."
```

2021-08-12 04:13 UTC, zero-24 commented
Merging now thanks for the review @blueforce and @tecpromotion

2021-08-12 04:13 UTC, merged