[4.1] Hide–able inline help in back– and frontend forms
joomlagerman/joomla pull request #2200
Opened 2022-01-05 19:58 UTC by tecpromotion

Pull Request für Issue #2125  .

### Zusammenfassung der Änderungen

add new/old strings

-> translation missing

### Wo wird der Sprachstring angezeigt / Wie kann getestet werden

all

2022-01-07 20:53 UTC, tecpromotion commented on language/de-DE/com_config.ini
> +COM_CONFIG_FIELD_DEFAULT_ACCESS_LEVEL_DESC="ie Standard-Zugriffsebene für neue Inhalte, Menüeinträge und andere Einträge."
```suggestion
COM_CONFIG_FIELD_DEFAULT_ACCESS_LEVEL_DESC="Die Standard-Zugriffsebene für neue Inhalte, Menüeinträge und andere Einträge."
```

2022-01-07 21:23 UTC, zero-24 requested changes

2022-01-07 21:23 UTC, zero-24 commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_FIELD_DEBUG_LANG_DESC="Auswählen, ob die Fehleranzeiger (<strong>** ... **</strong>) oder (<strong>?? ... ??</strong>) für die Joomla-Sprache angezeigt werden sollen. „Sprache debuggen“ fu
```suggestion
COM_CONFIG_FIELD_DEBUG_LANG_DESC="Auswählen, ob die Fehleranzeiger (<strong>** ... **</strong>) oder (<strong>?? ... ??</strong>) für die Joomla-Sprache angezeigt werden sollen. „Sprache debuggen“ funktioniert auch ohne die Aktivierung von „System debuggen“, zeigt dann allerdings nicht die benötigten zusätzlichen Informationen an, die bei der Korrektur der Fehler hilfreich wären."
```
Das ist keine Fehleranzeiger. "??" Steht dann bei jedem String. Man kann damit erkennen ob ein string via language string kommt oder nicht.

2022-01-07 21:23 UTC, zero-24 commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_FIELD_DEBUG_SYSTEM_DESC="Wenn aktiviert, werden diagnostische Informationen, Übersetzungen und SQL-Fehler (wenn vorhanden) angezeigt. Die Informationen werden auf jeder Seite im Joomla!-Ba
```suggestion
COM_CONFIG_FIELD_DEBUG_SYSTEM_DESC="Wenn aktiviert, werden diagnostische Informationen, Übersetzungs und SQL-Fehler, wenn vorhanden, angezeigt. Die Informationen werden auf jeder Seite im Joomla!-Backend und Frontend angezeigt.<br /><br /><strong>Warnung:</strong><br />Es wird ausdrücklich davon abgeraten, diese Informationen auf einer Liveseite anzuzeigen. Im Plugin 'System - Debug' kann die Ausgabe auch noch weiter konfiguriert und z.B. nur für bestimmte Benutzergruppen angezeigt werden."
```

2022-01-07 21:23 UTC, zero-24 commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_FIELD_DEFAULT_CAPTCHA_DESC="Die Standard Captcha-Einstellung für die Site auswählen. Eventuell müssen weitere Daten für das ausgewählte Captcha-Plugin unter „Plugins“ eingegeben werden."
Site? Hatten wir das nicht mal umgestellt?

2022-01-07 21:23 UTC, zero-24 commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_FIELD_DEFAULT_EDITOR_DESC="Den Standard-Texteditor auswählen. Registrierte Benutzer haben die Möglichkeit diese Einstellung in ihrem persönlichen Profil wieder zu überschreiben, wenn diese
```suggestion
COM_CONFIG_FIELD_DEFAULT_EDITOR_DESC="Den Standard-Texteditor auswählen. Registrierte Benutzer haben die Möglichkeit diese Einstellung in ihrem persönlichen Profil zu überschreiben."
```

2022-01-07 21:23 UTC, zero-24 commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_FIELD_ERROR_REPORTING_DESC="Die Empfindlichkeit der Fehlerbenachrichtigung kann aus der Drop-down-Liste ausgewählt werden.<br /><br /><strong>Hinweis:</strong><br />Auf den Hilfeseiten fin
```suggestion
COM_CONFIG_FIELD_ERROR_REPORTING_DESC="Die Empfindlichkeit der Fehlerbenachrichtigung kann aus der Drop-down-Liste ausgewählt werden.<br /><br /><strong>Hinweis:</strong><br />Auf den Hilfeseiten finden sich weitere Informationen."
```
Empfindlichkeiten hmm.

Auf den Hilfeseiten? Sollten wir die dann nicht verlinken?

2022-01-07 21:23 UTC, zero-24 commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_FIELD_GZIP_COMPRESSION_DESC="Sofern vom Webserver unterstützt, die Seitenausgabe komprimiert ausgeben (buffered output).<br /><br /><strong>Hinweis:</strong><br />Joomla! komprimiert dabei
```suggestion
COM_CONFIG_FIELD_GZIP_COMPRESSION_DESC="Sofern vom Webserver unterstützt, wird die Seitenausgabe komprimiert ausgeben (buffered output).<br /><br /><strong>Hinweis:</strong><br />Joomla! komprimiert dabei nur die generierte HTML-Seite. JavaScript, CSS, Bilder etc. werden <u>nicht</u> komprimiert."
```

2022-01-07 21:23 UTC, zero-24 commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_FIELD_LOG_PATH_DESC="Joomla kann optional eine Protokolldatei über seine eigenen Operationen und die von Erweiterungen von Drittanbietern speichern. Einen absoluten Pfad zu einem Ordner an
Warum wird joomla nicht geladen wenn es optional ist? Da sollten wir nochmal nachschauen

2022-01-07 21:23 UTC, zero-24 commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_FIELD_METAVERSION_DESC="Steuert, ob das Meta-Tag <code>generator</code> im Header des HTML-Dokuments im Frontend und in Atom-Feeds die genaue Version Ihrer Joomla-Site enthält. Es wird emp
```suggestion
COM_CONFIG_FIELD_METAVERSION_DESC="Steuert, ob der Meta-Tag <code>generator</code> im Header des HTML-Dokuments im Frontend und in Atom-Feeds die genaue Version Ihrer Joomla-Site enthält. Es wird empfohlen, diese Option aus Sicherheitsgründen zu deaktivieren."
```

2022-01-07 21:23 UTC, zero-24 commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_FIELD_SEF_SUFFIX_DESC="Standardmäßig sind Joomla-URLs „nackt“, ohne Erweiterung. Diese Option weist Joomla an, eine Erweiterung wie <code>.html</code>, <code>.feed</code> usw. basierend au
```suggestion
COM_CONFIG_FIELD_SEF_SUFFIX_DESC="Standardmäßig werden Joomla-URLs ohne Erweiterung ausgegeben. Diese Option weist Joomla an, eine Erweiterung wie <code>.html</code>, <code>.feed</code> usw. basierend auf der Art des Inhalts hinzuzufügen, der von der URL angezeigt wird."
```

2022-01-07 21:23 UTC, zero-24 commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_FIELD_SEF_URL_DESC="Joomla-URLs sehen normalerweise wie <code>index.php?option=com_example&task=item.display&id=1</code> aus, was weder mündlich noch schriftlich leicht zu vermitteln ist.
```suggestion
COM_CONFIG_FIELD_SEF_URL_DESC="Standardmäßig werden Joomla-URLs so ausgegeben <code>index.php?option=com_example&task=item.display&id=1</code>. Wenn Sie Suchmaschinenfreundliche (SEF) URLs aktivieren werden diese etwas leserlich angezeigt z.&#8239;B. <code>index.php/example/display/something</code>."
```

2022-01-07 21:23 UTC, zero-24 commented on language/de-DE/com_config.ini
> +COM_CONFIG_FIELD_SEF_URL_DESC="Joomla-URLs sehen normalerweise wie <code>index.php?option=com_example&task=item.display&id=1</code> aus, was weder mündlich noch schriftlich leicht zu vermitteln ist.
S.o.

2022-01-07 21:45 UTC, tecpromotion commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_FIELD_DEBUG_LANG_DESC="Auswählen, ob die Fehleranzeiger (<strong>** ... **</strong>) oder (<strong>?? ... ??</strong>) für die Joomla-Sprache angezeigt werden sollen. „Sprache debuggen“ fu
@zero-24 see 6c2bf51bfde6409c9ecf2b442511f87650eb445b

2022-01-07 21:50 UTC, tecpromotion commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_FIELD_ERROR_REPORTING_DESC="Die Empfindlichkeit der Fehlerbenachrichtigung kann aus der Drop-down-Liste ausgewählt werden.<br /><br /><strong>Hinweis:</strong><br />Auf den Hilfeseiten fin
@zero-24 see ee8573c966480a844fe71e5dc3b251c699a64c4e

2022-01-07 21:52 UTC, tecpromotion commented on administrator/language/de-DE/com_config.ini
> +COM_CONFIG_FIELD_LOG_PATH_DESC="Joomla kann optional eine Protokolldatei über seine eigenen Operationen und die von Erweiterungen von Drittanbietern speichern. Einen absoluten Pfad zu einem Ordner an
@zero-24 see https://github.com/joomla/joomla-cms/blob/9f4d126ba9d58e5ab6922c881d7009e7fe632494/administrator/language/en-GB/com_config.ini#L109

2022-01-17 19:36 UTC, zero-24 approved these changes

2022-01-17 19:36 UTC, merged

2022-01-17 19:36 UTC, zero-24 commented
Merged