Tiny/Medien einfügen - Korrektur CSS-Klasse Beschr
joomlagerman/joomla pull request #2262
Opened 2022-02-11 14:06 UTC by dozentis

vorher: _JFIELD_MEDIA_FIGURE_CLASS_LABEL="CSS-Klasse Bildunterschrift"_
Damit ist aber nicht die Bildunterschrift-Klasse `<figure-caption>`, sondern die CSS_Klasse des `<figure>`-Elements gemeint, siehe Bsp-Code nach Einfügen eines Bildes:
```
<figure class="image figure-css-klasse"><img class="bild-css-klasse" src="images/icon.png" alt="Bildbeschreibung Alt-Txt" width="96" height="96"  />
<figcaption>Eine Bildunterschrift</figcaption>
```

Ich schlage die Übersetzung vor:  _JFIELD_MEDIA_FIGURE_CLASS_LABEL="CSS-Klasse Bild-Container"_

PS: Bin übrigens neu auf github, und muß mich noch hier was einarbeiten  ;-)

Pull Request für Issue # .

### Zusammenfassung der Änderungen

### Wo wird der Sprachstring angezeigt / Wie kann getestet werden

2022-02-11 14:20 UTC, tecpromotion requested changes

2022-02-11 14:20 UTC, tecpromotion commented on language/de-DE/joomla.ini
> +JFIELD_MEDIA_FIGURE_CLASS_LABEL="CSS-Klasse Bild-Container"
```suggestion
JFIELD_MEDIA_FIGURE_CLASS_LABEL="CSS-Klasse Abbildung"
```
Das wäre etwas allgemeiner. Auch OK? @dozentis ?

2022-02-11 14:22 UTC, tecpromotion commented
Diese beiden Stellen müssen dann ebenfalls angepasst werden @dozentis 

https://github.com/joomlagerman/joomla/blob/b2ee0030ea0490cf5e23390a108efdb24516bc7c/administrator/language/de-DE/joomla.ini#L253
https://github.com/joomlagerman/joomla/blob/b2ee0030ea0490cf5e23390a108efdb24516bc7c/api/language/de-DE/joomla.ini#L252

2022-02-11 14:47 UTC, dozentis commented on language/de-DE/joomla.ini
> +JFIELD_MEDIA_FIGURE_CLASS_LABEL="CSS-Klasse Bild-Container"
Ich hatte tatsächlich "Abbildung" auch als 2. mögliche Option geschrieben, dann diese rausgenommen und mich auf Bild-Container festgelegt, da ich finde dass in dieser Maske damit der Zweck des Feldes besser verstanden werden kann, als Abbildung (was natürlich die sinngemäße Übersetzung ist)

 [https://www.mediaevent.de/html/figure-figcaption.html](url)
> HTML figure ist ein Container für Bilder, Grafiken und andere Abbildungen

2022-02-11 15:01 UTC, dozentis commented on language/de-DE/joomla.ini
> +JFIELD_MEDIA_FIGURE_CLASS_LABEL="CSS-Klasse Bild-Container"
Nochmal nachgedacht: Da über CMS-Inhalte/Medien einfügen auch neben Bilder, auch audio/video/object  Elemente geladen werden können, wäre vielleicht sogar "CSS Klasse Medien-Container" passender? 🤔

2022-02-12 08:13 UTC, tecpromotion requested changes
@dozentis bitte die Änderungen noch einbringen, dann landet es Dienstag noch in der 4.1.0.1

2022-02-12 08:13 UTC, tecpromotion commented on language/de-DE/joomla.ini
> +JFIELD_MEDIA_FIGURE_CLASS_LABEL="CSS-Klasse Bild-Container"
```suggestion
JFIELD_MEDIA_FIGURE_CLASS_LABEL="CSS-Klasse figure-Element"
```

Das trifft es doch ganz gut. 
Container ist mir zu weit weg. 

https://wiki.selfhtml.org/wiki/HTML/Elemente/figure

2022-02-13 18:48 UTC, tecpromotion approved these changes

2022-02-13 18:48 UTC, tecpromotion commented
@zero-24 please check this 3 strings.

2022-02-14 07:27 UTC, dozentis commented on language/de-DE/joomla.ini
> +JFIELD_MEDIA_FIGURE_CLASS_LABEL="CSS-Klasse Bild-Container"
CSS Klasse Medien-Element? figure-Element ist auch gut. Ich schau heute Nachmittag nochmal rein, dann machen wir das heute fix

2022-02-14 08:52 UTC, tecpromotion commented on language/de-DE/joomla.ini
> +JFIELD_MEDIA_FIGURE_CLASS_LABEL="CSS-Klasse Bild-Container"
Da es sich direkt auf das HTML-figure bezieht, bringt Medien-Element wieder eine Unschärfe rein.

2022-02-14 14:34 UTC, dozentis commented on language/de-DE/joomla.ini
> +JFIELD_MEDIA_FIGURE_CLASS_LABEL="CSS-Klasse Bild-Container"
Ich habe die beiden editiert, ich hoffe im richtigen Branch. Benötigen die einen erneuten Pull? Wie gesagt, ich muss mich noch auf github einfinden, und bräuchte eventuell eure Unterstützung. Danke. 


> https://github.com/joomlagerman/joomla/blob/b2ee0030ea0490cf5e23390a108efdb24516bc7c/administrator/language/de-DE/joomla.ini#L253
> 
> 
> https://github.com/joomlagerman/joomla/blob/b2ee0030ea0490cf5e23390a108efdb24516bc7c/api/language/de-DE/joomla.ini#L252

2022-02-14 14:41 UTC, tecpromotion commented on language/de-DE/joomla.ini
> +JFIELD_MEDIA_FIGURE_CLASS_LABEL="CSS-Klasse Bild-Container"
Ich hatte doch alle schon auf figure-Element geändert :)

2022-02-14 14:57 UTC, merged