[4.1] improve plg_editors_tinymce
joomlagerman/joomla pull request #2279
Opened 2022-02-18 16:40 UTC by tecpromotion

Pull Request für Issue #2276 PR #2277 and PR #2278 

### Zusammenfassung der Änderungen

optimize some strings

@7at1blow please check

### Wo wird der Sprachstring angezeigt / Wie kann getestet werden

backend

2022-02-18 20:04 UTC, 7at1blow requested changes
Code 2279 Zeile 55:
"Dieses Set zuweisen" halte ich noch nicht für passend, m. E. besser "Diesem Set zuweisen:", also Diesem und am Ende mit Doppelpunkt, weil hinter dem Doppelpunkt ja das folgt, was dem Set zugewiesen werden kann. Also so wie ich das verstehe, wird doch dem ausgewählten Set etwas zugewiesen und nicht ein Set irgendwas anderem zugewiesen.

Zeile 90:
Müsste das nicht an der Stelle "Das unten stehende Panel ... jede Voreinstellung ..." statt "... jedes Set ..." heißen? Eigentlich passt sogar beides, ist an der Stelle beides zutreffend: "... jedes Set und jede Voreinstellung ...", oder?

2022-02-18 20:10 UTC, tecpromotion commented
> Code 2279 Zeile 55: "Dieses Set zuweisen" halte ich noch nicht für passend, m. E. besser "Diesem Set zuweisen:", also Diesem und am Ende mit Doppelpunkt, weil hinter dem Doppelpunkt ja das folgt, was dem Set zugewiesen werden kann. Also so wie ich das verstehe, wird doch dem ausgewählten Set etwas zugewiesen und nicht ein Set irgendwas anderem zugewiesen.

Einem Set werden eine oder mehrere Benutzergruppen zugeordnet.
Original: "Assign this Set to" und dann folgt die Auswahl der Benutzergruppen.

> Zeile 90: Müsste das nicht an der Stelle "Das unten stehende Panel ... jede Voreinstellung ..." statt "... jedes Set ..." heißen? Eigentlich passt sogar beides, ist an der Stelle beides zutreffend: "... jedes Set und jede Voreinstellung ...", oder?

Voreinstellungen sind mMn hier die farbigen Buttons, quasi Presets, die dann eine Vorauswahl bereits haben und so einer Voreinstellung entsprechen.

Was meinst du dazu @zero-24 ?

2022-02-18 20:31 UTC, 7at1blow commented
Ja, im Englischen steht zwar "Assign this Set to", aber wie ja heute schon mal schrieb: Müsste das im Englischen nicht stattdessen "Assign this to Set:" heißen? Weil, nicht das Set wird zugewiesen, sondern dem Set wird (Nachfolgendes) zugewiesen, oder?

2022-02-18 20:39 UTC, tecpromotion commented
> Ja, im Englischen steht zwar "Assign this Set to", aber wie ja heute schon mal schrieb: Müsste das im Englischen nicht stattdessen "Assign this to Set:" heißen? Weil, nicht das Set wird zugewiesen, sondern dem Set wird (Nachfolgendes) zugewiesen, oder?

Das ist richtig im englischen mMn.

2022-02-18 21:07 UTC, 7at1blow commented
Ah, ich glaube, jetzt habe ich wieder was verstanden.
An der Stelle ist nur gemeint, dass dieses (ausgewählte) Set folgenden Benutzergruppen zugewiesen wird. Dann passt das auch mit "Assign this Set to:"

Ich hatte es bislang so verstanden, dass sich die Aussage hier nicht nur auf die Benutzergruppen bezieht, sondern auf alles was rechts von diesem "Assign ..." steht UND ZUSÄTZLICH auch auf das, was darunter angeführt ist - also auch die Voreinstellungen (Einfache, Mittlere, ...) inkl. den individuellen Modifikationen der Schaltflächen im TinyMCE-Menü. Sorry für die Umstände, die ich Euch mit meinem Nichtverstehen bereitet habe.

2022-02-18 21:13 UTC, tecpromotion commented
Ich bin sehr froh, dass du dich damit beschäftigst und hoffe du steuerst bald eigene PRs bei.
Wir brauchen dringend mehr Hilfe hier.

2022-02-19 22:57 UTC, zero-24 approved these changes

2022-02-19 22:57 UTC, merged

2022-02-19 22:58 UTC, zero-24 commented
Merging dank euch :-)