[4][scheduler] sort by last run
joomlagerman/joomla pull request #2449
Opened 2022-05-14 07:21 UTC by heelc29

Pull Request für Issue #2445 .

### Zusammenfassung der Änderungen

add strings

### Wo wird der Sprachstring angezeigt / Wie kann getestet werden

backend (com_scheduler/tasks)
![image](https://user-images.githubusercontent.com/66922325/168415450-28d7b8e8-7bb9-4c98-9164-ef000016a5d5.png)

2022-05-14 07:22 UTC, heelc29 commented
Evtl. etwas lang?

2022-05-14 09:49 UTC, tecpromotion commented
> Evtl. etwas lang?

Letztes weglassen. Wenn ich nach dem Datum sortiere sollte das obligatorisch sein.

2022-05-14 15:07 UTC, tecpromotion requested changes
Letztes ist im deutschen zu lang und auch nicht zwingend notwendig m.M.n.

2022-05-14 15:07 UTC, tecpromotion commented on administrator/language/de-DE/com_scheduler.ini
> +COM_SCHEDULER_LAST_RUN_ASC="Letztes Ausführungsdatum aufsteigend"
```suggestion
COM_SCHEDULER_LAST_RUN_ASC="Ausführungsdatum aufsteigend"
```

2022-05-14 15:07 UTC, tecpromotion commented on administrator/language/de-DE/com_scheduler.ini
> +COM_SCHEDULER_LAST_RUN_DESC="Letztes Ausführungsdatum absteigend"
```suggestion
COM_SCHEDULER_LAST_RUN_DESC="Ausführungsdatum absteigend"
```

2022-05-16 10:38 UTC, tecpromotion approved these changes

2022-05-16 10:38 UTC, merged