[4.2] Smart Search: Allow fuzzy word matching
joomlagerman/joomla pull request #2466
Opened 2022-06-05 06:53 UTC by heelc29

Pull Request für Issue #2457 .

### Zusammenfassung der Änderungen

add strings

### Wo wird der Sprachstring angezeigt / Wie kann getestet werden

backend (com_config/component/com_finder)
![image](https://user-images.githubusercontent.com/66922325/172038994-fc036fc6-562f-430d-8aa2-9c453ee2cffa.png)
![image](https://user-images.githubusercontent.com/66922325/172039171-6ece131c-a7aa-4604-ae23-910e2253af27.png)

2022-06-05 17:44 UTC, tecpromotion requested changes
Translation

2022-06-05 17:44 UTC, tecpromotion commented on administrator/language/de-DE/com_finder.ini
> +COM_FINDER_CONFIG_WORD_MATCH_DESC="Legt fest, wie Suchbegriffe mit dem Index übereinstimmen müssen. Standardmäßig muss ein Wort genau übereinstimmen, sollte eine Sprache aber zusammengesetzte Wörter
...der Wörtern...

Meintest du das @heelc29 ?

2022-06-06 06:19 UTC, heelc29 commented on administrator/language/de-DE/com_finder.ini
> +COM_FINDER_CONFIG_WORD_MATCH_DESC="Legt fest, wie Suchbegriffe mit dem Index übereinstimmen müssen. Standardmäßig muss ein Wort genau übereinstimmen, sollte eine Sprache aber zusammengesetzte Wörter
Oder soll man das ganz weglassen - einfach nur `am Anfang oder an einer beliebigen Stelle innerhalb des Index`

2022-06-06 20:16 UTC, tecpromotion approved these changes
Thanks @heelc29

2022-06-06 20:16 UTC, merged