[4.x] Com Finder translation is wrong
joomlagerman/joomla pull request #2476
Opened 2022-06-09 14:02 UTC by tecpromotion

Pull Request für Issue #2475 .

### Zusammenfassung der Änderungen

fix wording

### Wo wird der Sprachstring angezeigt / Wie kann getestet werden

frontend

2022-06-09 14:03 UTC, tecpromotion commented
@chmst Please check

2022-06-09 14:07 UTC, chmst commented
Perfekt! Schnelle Arbeit :)

2022-06-09 19:03 UTC, heelc29 requested changes
`%2` wird ja noch mit folgenden Strings ergänzt:
https://github.com/joomlagerman/joomla/blob/3ae1953405ef55b04e92025cc64f59bc5b8a1cdc/language/de-DE/com_finder.ini#L41-L44

_Ausgehend von_ scheint mir etwas "unvollständig":
![image](https://user-images.githubusercontent.com/66922325/172922830-4a7201d9-aa83-4c50-a96a-a34ff95b595a.png)

Optionen??
_Unter der Annahme, dass_ „joomla“ benötigt wird, wurden folgende 12 Ergebnisse gefunden.
_Ausgehend davon, dass_ „joomla“ benötigt wird, wurden folgende 12 Ergebnisse gefunden.
_Vorausgesetzt, dass_ „joomla“ benötigt wird, wurden folgende 12 Ergebnisse gefunden.

2022-06-09 19:03 UTC, heelc29 commented on language/de-DE/com_finder.ini
> +COM_FINDER_QUERY_RESULTS_1="Ausgehend von %2$s, wurden folgende Ergebnisse gefunden:"
```suggestion
COM_FINDER_QUERY_RESULTS_1="Ausgehend von %2$s, wurde folgendes Ergebnis gefunden."
```
Singular:
![image](https://user-images.githubusercontent.com/66922325/172921208-3ff388d6-05ce-43ea-b0fa-5d078f9c7e42.png)

2022-06-09 19:11 UTC, tecpromotion commented
@chmst Hattest du das nicht geprüft?

2022-06-09 19:12 UTC, chmst commented
Ich hatte die drei markierten strings geprüft

2022-06-10 10:22 UTC, zero-24 approved these changes

2022-06-10 10:23 UTC, zero-24 commented
Aus meiner Sicht so ok soll ich mergen oder steht noch eine Änderung aus?

2022-06-10 12:15 UTC, chmst commented
Ausgehend davon, dass „asfasdfasdfasdf“ benötigt wird und mit „Christiane“ als „Autor“ und mit „*“ als „Sprache“ und mit „Beiträge“ als „Typ“ , wurde kein Ergebnis gefunden

so schauts aus ...

2022-06-10 15:01 UTC, tecpromotion commented
@heelc29 noch Anmerkungen?

2022-06-10 16:26 UTC, heelc29 approved these changes
Für mich ist das auch in Ordnung hier:
![image](https://user-images.githubusercontent.com/66922325/173109975-2fad5dae-17ed-4153-8777-5b072d5c7981.png)
![image](https://user-images.githubusercontent.com/66922325/173109843-9c0815b1-62e4-48ff-b564-e6b45fa42350.png)
![image](https://user-images.githubusercontent.com/66922325/173109928-68a80f12-b2c7-4225-9c69-65bec9365c4c.png)

Hier noch mal ein deutsch/englisch Vergleich:
![image](https://user-images.githubusercontent.com/66922325/173109494-6aeaae68-3aac-4792-9f0d-67bbef04c36c.png)
![image](https://user-images.githubusercontent.com/66922325/173109546-ece09d80-d303-4613-8a2f-96961370900c.png)

2022-06-10 16:48 UTC, merged