[4.2] update message
joomlagerman/joomla pull request #2498
Opened 2022-06-17 10:30 UTC by tecpromotion

Pull Request für Issue #2494 .

### Zusammenfassung der Änderungen

translation

### Wo wird der Sprachstring angezeigt / Wie kann getestet werden

backend

2022-06-17 11:07 UTC, zero-24 approved these changes, later dismissed

2022-06-17 11:44 UTC, heelc29 requested changes
Die beiden Formulierungen sollten ähnlich sein!? Das war doch der Auslöser des PR...
![image](https://user-images.githubusercontent.com/66922325/174291823-918f176a-7fb9-494b-a722-46194ed953bb.png)

2022-06-17 11:47 UTC, tecpromotion commented
Welche Formulierung wird von euch bevorzugt?

2022-06-17 12:03 UTC, max123kl commented
Ich werfe mal eine neue Formulierung in die Runde:
"Die Warnungen über möglicherweise inkompatible Erweiterungen **akzeptieren** und ..."

2022-06-17 12:29 UTC, heelc29 commented
Wäre für **zur Kenntnis nehmen**, aber **akzeptieren** finde ich auch gut 😀
**Update** kommt auf der Seite - und der Button auch - jedenfalls häufiger vor:
![image](https://user-images.githubusercontent.com/66922325/174298063-f3c2b707-309d-4af1-a1d5-ff7ae4594f76.png)
![image](https://user-images.githubusercontent.com/66922325/174298288-1201caf1-35f5-4522-b95b-8776512e554a.png)

2022-06-17 16:53 UTC, zero-24 approved these changes

2022-06-18 04:58 UTC, max123kl approved these changes

2022-06-18 06:31 UTC, zero-24 approved these changes

2022-06-18 06:31 UTC, merged