[4.2] [GSoC 21] Keyboard-Shortcut Plugin
joomlagerman/joomla pull request #2513
Opened 2022-06-24 16:29 UTC by heelc29

Pull Request für Issue #2509 .

### Zusammenfassung der Änderungen

add two files

### Wo wird der Sprachstring angezeigt / Wie kann getestet werden

backend (com_plugins/plugin/edit)
![image](https://user-images.githubusercontent.com/66922325/175577422-fa6d80f6-dc1d-4836-bdae-6257189846a1.png)

backend
![image](https://user-images.githubusercontent.com/66922325/175577514-8e694444-0f3c-450a-b91f-d8e4015b572c.png)
![image](https://user-images.githubusercontent.com/66922325/175577528-a71d1628-4c69-4348-960e-542540e06f70.png)

2022-06-24 18:25 UTC, tecpromotion commented on administrator/language/de-DE/plg_system_shortcut.ini
> +PLG_SYSTEM_SHORTCUT_OVERVIEW_HINT="<span class=\"icon-keyboard fa-keyboard me-2\" aria-hidden=\"true\"></span> <kbd>J</kbd> + <kbd>X</kbd> <small>Tastenkombinationen</small>"
```suggestion
PLG_SYSTEM_SHORTCUT_OVERVIEW_HINT="<span class='icon-keyboard fa-keyboard me-2' aria-hidden='true'></span> <kbd>J</kbd> + <kbd>X</kbd> <small>Tastenkombinationen</small>"
```

2022-06-24 18:25 UTC, tecpromotion commented on administrator/language/de-DE/plg_system_shortcut.ini
> +PLG_SYSTEM_SHORTCUT_XML_DESCRIPTION="<p>Ermöglicht Tastenkombinationen in der Administration, die von anderen Plugins zur Verfügung gestellt werden können, und enthält bereits folgende Tastenkombinat
```suggestion
PLG_SYSTEM_SHORTCUT_XML_DESCRIPTION="<p>Ermöglicht Tastenkombinationen in der Administration, die von anderen Plugins zur Verfügung gestellt werden können, und enthält bereits folgende Tastenkombinationen:</p><ul class='list-unstyled'><li><kbd>J</kbd> <kbd>A</kbd> Speichern</li><li><kbd>J</kbd> <kbd>S</kbd> Speichern &amp; Schließen</li><li><kbd>J</kbd> <kbd>Q</kbd> Abbrechen</li><li><kbd>J</kbd> <kbd>N</kbd> Neu</li><li><kbd>J</kbd> <kbd>F</kbd> Suchen</li><li><kbd>J</kbd> <kbd>O</kbd> Optionen</li><li><kbd>J</kbd> <kbd>H</kbd> Hilfe</li><li><kbd>J</kbd> <kbd>X</kbd> Übersicht</li><li><kbd>J</kbd> <kbd>D</kbd> Dashboard</li></ul>"
```

2022-06-24 18:26 UTC, tecpromotion commented on administrator/language/de-DE/plg_system_shortcut.sys.ini
> +PLG_SYSTEM_SHORTCUT_XML_DESCRIPTION="<p>Ermöglicht Tastenkombinationen in der Administration, die von anderen Plugins zur Verfügung gestellt werden können, und enthält bereits folgende Tastenkombinat
```suggestion
PLG_SYSTEM_SHORTCUT_XML_DESCRIPTION="<p>Ermöglicht Tastenkombinationen in der Administration, die von anderen Plugins zur Verfügung gestellt werden können, und enthält bereits folgende Tastenkombinationen:</p><ul class='list-unstyled'><li><kbd>J</kbd> <kbd>A</kbd> Speichern</li><li><kbd>J</kbd> <kbd>S</kbd> Speichern &amp; Schließen</li><li><kbd>J</kbd> <kbd>Q</kbd> Abbrechen</li><li><kbd>J</kbd> <kbd>N</kbd> Neu</li><li><kbd>J</kbd> <kbd>F</kbd> Suchen</li><li><kbd>J</kbd> <kbd>O</kbd> Optionen</li><li><kbd>J</kbd> <kbd>H</kbd> Hilfe</li><li><kbd>J</kbd> <kbd>X</kbd> Übersicht</li><li><kbd>J</kbd> <kbd>D</kbd> Dashboard</li></ul>"
```

2022-06-24 18:27 UTC, tecpromotion requested changes
we use `class='...'` instead of `class="..."`

2022-06-25 11:55 UTC, tecpromotion commented
Still WIP @heelc29 ?

2022-06-27 09:51 UTC, heelc29 commented
@tecpromotion War noch am überlegen (`PLG_SYSTEM_SHORTCUT_OVERVIEW_DESC`) - mir fällt gerade aber nichts "besseres" ein.

2022-06-27 10:12 UTC, tecpromotion approved these changes

2022-06-27 10:12 UTC, merged