[4.3] Quickicons
joomlagerman/joomla pull request #2674
Opened 2022-11-19 14:14 UTC by zero-24

Pull Request für Issue #2660

### Zusammenfassung der Änderungen

Neue Optionen im Quickicons modul

### Wo wird der Sprachstring angezeigt / Wie kann getestet werden

Quickicons modul

2022-11-20 13:31 UTC, heelc29 requested changes

2022-11-20 13:31 UTC, heelc29 commented on administrator/language/de-DE/com_banners.ini
> +COM_BANNERS_N_QUICKICON_SRONLY_1="Banners: Ein Banner ist verfügbar"
```suggestion
COM_BANNERS_N_QUICKICON="Banner"
COM_BANNERS_N_QUICKICON_1="Banner"
COM_BANNERS_N_QUICKICON_SRONLY="Banner: %d Banner sind verfügbar."
COM_BANNERS_N_QUICKICON_SRONLY_1="Banner: Ein Banner ist verfügbar."
```

2022-11-20 13:31 UTC, heelc29 commented on administrator/language/de-DE/com_content.ini
> +COM_CONTENT_FEATURED_N_QUICKICON_1="Hauptbeiträge"
```suggestion
COM_CONTENT_FEATURED_N_QUICKICON="Hauptbeiträge"
COM_CONTENT_FEATURED_N_QUICKICON_1="Hauptbeitrag"
```

2022-11-20 13:31 UTC, heelc29 commented on administrator/language/de-DE/mod_quickicon.ini
> +MOD_QUICKICON_BANNER_MANAGER_ADD="Neuer Banner"
```suggestion
MOD_QUICKICON_BANNER_MANAGER="Banner"
MOD_QUICKICON_BANNER_MANAGER_ADD="Neues Banner"
```

2022-11-20 13:31 UTC, heelc29 commented on administrator/language/de-DE/mod_quickicon.ini
> +MOD_QUICKICON_CONTACT_MANAGER_ADD="Neuer Kontakte"
```suggestion
MOD_QUICKICON_CONTACT_MANAGER_ADD="Neuer Kontakt"
```

2022-11-20 13:31 UTC, heelc29 commented on administrator/language/de-DE/mod_quickicon.ini
> +MOD_QUICKICON_SHOW_FEATURED_LABEL="Hauptbeitrag"
```suggestion
MOD_QUICKICON_SHOW_FEATURED_LABEL="Hauptbeiträge"
```

2022-11-20 13:31 UTC, heelc29 commented on administrator/language/de-DE/mod_quickicon.ini
> +MOD_QUICKICON_SHOW_WORKFLOW_LABEL="Workflow"
```suggestion
MOD_QUICKICON_SHOW_WORKFLOW_LABEL="Workflows"
```

2022-11-20 13:31 UTC, heelc29 commented on administrator/language/de-DE/mod_quickicon.ini
> +MOD_QUICKICON_TEMPLATE_STYLES="Template Styles"
```suggestion
MOD_QUICKICON_TEMPLATE_STYLES="Template Stile"
```

2022-11-29 16:31 UTC, tecpromotion approved these changes

2022-11-29 16:32 UTC, merged