[4.3] GSoC’22 project: Guided Tours
joomlagerman/joomla pull request #2778
Opened 2023-04-01 14:46 UTC by heelc29

Pull Request für Issue #2770, #2772, #2775, #2776 und #2777 .

### Zusammenfassung der Änderungen

add strings
add copyright

### Wo wird der Sprachstring angezeigt / Wie kann getestet werden

backend

2023-04-01 15:08 UTC, heelc29 commented
com_admin/help
![image](https://user-images.githubusercontent.com/66922325/229297184-62c3d68c-5543-45f5-838d-bca1d49acfb2.png)

com_guidedtours/step/edit
![image](https://user-images.githubusercontent.com/66922325/229297180-8b2c1596-42d3-4ad6-b368-6c28174fe29b.png)

com_cpanel/cpanel/system
![image](https://user-images.githubusercontent.com/66922325/229297192-453afceb-aa17-4079-86b5-fb5c27d85ee2.png)

com_modules/modules
![image](https://user-images.githubusercontent.com/66922325/229297228-7b150c57-b7e9-471a-8e3d-ca7cd11859b9.png)

2023-04-01 15:25 UTC, heelc29 commented
com_modules/select
![image](https://user-images.githubusercontent.com/66922325/229298179-b238577a-baf3-4016-8549-320896710df4.png)

com_modules/module/edit
![image](https://user-images.githubusercontent.com/66922325/229298171-bba5a460-9ed8-4e43-896f-0bc3689fdf20.png)

cpanel/status
![image](https://user-images.githubusercontent.com/66922325/229298173-a91b263f-e146-40bb-a985-b3a081c1dcb0.png)
![image](https://user-images.githubusercontent.com/66922325/229298174-c9a4dd14-b217-4247-86dc-c7f0cf4fbe96.png)

2023-04-02 10:02 UTC, heelc29 commented
![image](https://user-images.githubusercontent.com/66922325/229345972-0628391c-9dfd-49da-9a98-23b571be1c3b.png)
![image](https://user-images.githubusercontent.com/66922325/229345836-bc2b44e5-b4d0-476b-a7fa-97a3f3ba74eb.png)
![image](https://user-images.githubusercontent.com/66922325/229345846-881f80fc-2790-459f-b99b-1a2fca6a8540.png)
![image](https://user-images.githubusercontent.com/66922325/229345860-9b2a8be5-4893-40f9-9725-58c2d848fcca.png)
![image](https://user-images.githubusercontent.com/66922325/229345876-8375c3d5-36f1-4e7d-be4b-3642513c536a.png)
![image](https://user-images.githubusercontent.com/66922325/229345885-f7175b4d-9eeb-4fd6-91e0-9679c47f76ef.png)

2023-04-16 07:09 UTC, zero-24 requested changes
Eintrag vs Tour/Touren ;)

2023-04-16 07:09 UTC, zero-24 commented on administrator/language/de-DE/com_guidedtours.ini
> +COM_GUIDEDTOURS_N_ITEMS_ARCHIVED_1="Eintrag wurde archiviert."
```suggestion
COM_GUIDEDTOURS_N_ITEMS_ARCHIVED_1="Tour wurde archiviert."
```

2023-04-16 07:09 UTC, zero-24 commented on administrator/language/de-DE/com_guidedtours.ini
> +COM_GUIDEDTOURS_N_ITEMS_ARCHIVED="%d Einträge wurden archiviert."
```suggestion
COM_GUIDEDTOURS_N_ITEMS_ARCHIVED="%d Touren wurden archiviert."
```

2023-04-16 07:09 UTC, zero-24 commented on administrator/language/de-DE/com_guidedtours.ini
> +COM_GUIDEDTOURS_N_ITEMS_CHECKED_IN_1="Eintrag wurde freigegeben."
```suggestion
COM_GUIDEDTOURS_N_ITEMS_CHECKED_IN_1="Tour wurde freigegeben."
```

2023-04-16 07:09 UTC, zero-24 commented on administrator/language/de-DE/com_guidedtours.ini
> +COM_GUIDEDTOURS_N_ITEMS_CHECKED_IN_MORE="%d Einträge wurden freigegeben."
```suggestion
COM_GUIDEDTOURS_N_ITEMS_CHECKED_IN_MORE="%d Touren wurden freigegeben."
```

2023-04-16 07:09 UTC, zero-24 commented on administrator/language/de-DE/com_guidedtours.ini
> +COM_GUIDEDTOURS_N_ITEMS_DELETED_1="Eintrag wurde gelöscht."
```suggestion
COM_GUIDEDTOURS_N_ITEMS_DELETED_1="Tour wurde gelöscht."
```

2023-04-16 07:09 UTC, zero-24 commented on administrator/language/de-DE/com_guidedtours.ini
> +COM_GUIDEDTOURS_N_ITEMS_DELETED="%d Einträge wurden gelöscht."
```suggestion
COM_GUIDEDTOURS_N_ITEMS_DELETED="%d Touren wurden gelöscht."
```

2023-04-16 07:09 UTC, zero-24 commented on administrator/language/de-DE/com_guidedtours.ini
> +COM_GUIDEDTOURS_N_ITEMS_PUBLISHED_1="Eintrag wurde veröffentlicht."
```suggestion
COM_GUIDEDTOURS_N_ITEMS_PUBLISHED_1="Tour wurde veröffentlicht."
```

2023-04-16 07:09 UTC, zero-24 commented on administrator/language/de-DE/com_guidedtours.ini
> +COM_GUIDEDTOURS_N_ITEMS_PUBLISHED="%d Einträge wurden veröffentlicht."
```suggestion
COM_GUIDEDTOURS_N_ITEMS_PUBLISHED="%d Touren wurden veröffentlicht."
```

2023-04-16 07:09 UTC, zero-24 commented on administrator/language/de-DE/com_guidedtours.ini
> +COM_GUIDEDTOURS_N_ITEMS_TRASHED_1="Eintrag wurde in den Papierkorb verschoben."
```suggestion
COM_GUIDEDTOURS_N_ITEMS_TRASHED_1="Tour wurde in den Papierkorb verschoben."
```

2023-04-16 07:09 UTC, zero-24 commented on administrator/language/de-DE/com_guidedtours.ini
> +COM_GUIDEDTOURS_N_ITEMS_TRASHED="%d Einträge wurden in den Papierkorb verschoben."
```suggestion
COM_GUIDEDTOURS_N_ITEMS_TRASHED="%d Touren wurden in den Papierkorb verschoben."
```

2023-04-16 07:09 UTC, zero-24 commented on administrator/language/de-DE/com_guidedtours.ini
> +COM_GUIDEDTOURS_N_ITEMS_UNPUBLISHED_1="Eintrag wurden versteckt."
```suggestion
COM_GUIDEDTOURS_N_ITEMS_UNPUBLISHED_1="Tour wurde versteckt."
```

2023-04-16 07:09 UTC, zero-24 commented on administrator/language/de-DE/com_guidedtours.ini
> +COM_GUIDEDTOURS_N_ITEMS_UNPUBLISHED="%d Einträge wurde versteckt."
```suggestion
COM_GUIDEDTOURS_N_ITEMS_UNPUBLISHED="%d Touren wurden versteckt."
```

2023-04-16 07:10 UTC, zero-24 commented
Gibts einen Grund warum die Datei: [com_guidedtours.sys.ini](https://github.com/joomlagerman/joomla/pull/2778/files#diff-0e03d9bf3e46cc092f460d14b8349d87b0eae72869e7012f8ad0d97e6ef19353) nicht übersetzt ist?

2023-04-16 10:34 UTC, heelc29 commented on administrator/language/de-DE/com_guidedtours.ini
> +COM_GUIDEDTOURS_N_ITEMS_ARCHIVED_1="Eintrag wurde archiviert."
Geht leider nicht, da die Strings aktuell für Touren **und** Schritte verwendet werden.

2023-04-16 10:34 UTC, heelc29 commented on administrator/language/de-DE/com_guidedtours.ini
> +COM_GUIDEDTOURS_N_ITEMS_ARCHIVED="%d Einträge wurden archiviert."
Geht leider nicht, da die Strings aktuell für Touren **und** Schritte verwendet werden.

2023-04-16 10:34 UTC, heelc29 commented on administrator/language/de-DE/com_guidedtours.ini
> +COM_GUIDEDTOURS_N_ITEMS_CHECKED_IN_1="Eintrag wurde freigegeben."
Geht leider nicht, da die Strings aktuell für Touren **und** Schritte verwendet werden.

2023-04-16 10:34 UTC, heelc29 commented on administrator/language/de-DE/com_guidedtours.ini
> +COM_GUIDEDTOURS_N_ITEMS_CHECKED_IN_MORE="%d Einträge wurden freigegeben."
Geht leider nicht, da die Strings aktuell für Touren **und** Schritte verwendet werden.

2023-04-16 10:34 UTC, heelc29 commented on administrator/language/de-DE/com_guidedtours.ini
> +COM_GUIDEDTOURS_N_ITEMS_DELETED_1="Eintrag wurde gelöscht."
Geht leider nicht, da die Strings aktuell für Touren **und** Schritte verwendet werden.

2023-04-16 10:35 UTC, heelc29 commented on administrator/language/de-DE/com_guidedtours.ini
> +COM_GUIDEDTOURS_N_ITEMS_DELETED="%d Einträge wurden gelöscht."
Geht leider nicht, da die Strings aktuell für Touren **und** Schritte verwendet werden.

2023-04-16 10:35 UTC, heelc29 commented on administrator/language/de-DE/com_guidedtours.ini
> +COM_GUIDEDTOURS_N_ITEMS_PUBLISHED_1="Eintrag wurde veröffentlicht."
Geht leider nicht, da die Strings aktuell für Touren **und** Schritte verwendet werden.

2023-04-16 10:35 UTC, heelc29 commented on administrator/language/de-DE/com_guidedtours.ini
> +COM_GUIDEDTOURS_N_ITEMS_PUBLISHED="%d Einträge wurden veröffentlicht."
Geht leider nicht, da die Strings aktuell für Touren **und** Schritte verwendet werden.

2023-04-16 10:35 UTC, heelc29 commented on administrator/language/de-DE/com_guidedtours.ini
> +COM_GUIDEDTOURS_N_ITEMS_TRASHED_1="Eintrag wurde in den Papierkorb verschoben."
Geht leider nicht, da die Strings aktuell für Touren **und** Schritte verwendet werden.

2023-04-16 10:35 UTC, heelc29 commented on administrator/language/de-DE/com_guidedtours.ini
> +COM_GUIDEDTOURS_N_ITEMS_UNPUBLISHED_1="Eintrag wurden versteckt."
Geht leider nicht, da die Strings aktuell für Touren **und** Schritte verwendet werden.

2023-04-16 10:35 UTC, heelc29 commented on administrator/language/de-DE/com_guidedtours.ini
> +COM_GUIDEDTOURS_N_ITEMS_TRASHED="%d Einträge wurden in den Papierkorb verschoben."
Geht leider nicht, da die Strings aktuell für Touren **und** Schritte verwendet werden.

2023-04-16 10:35 UTC, heelc29 commented on administrator/language/de-DE/com_guidedtours.ini
> +COM_GUIDEDTOURS_N_ITEMS_UNPUBLISHED="%d Einträge wurde versteckt."
Geht leider nicht, da die Strings aktuell für Touren **und** Schritte verwendet werden.

2023-04-16 10:38 UTC, tecpromotion commented
Hat noch keiner gemacht. Sitzen ja noch drüber.

2023-04-16 11:09 UTC, heelc29 commented on administrator/language/de-DE/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_SMARTSEARCH_TITLE="Wie erstellt man intelligente Suchfilter??"
```suggestion
COM_GUIDEDTOURS_TOUR_SMARTSEARCH_TITLE="Wie erstellt man intelligente Suchfilter?"
```

2023-04-17 14:59 UTC, zero-24 commented on administrator/language/de-DE/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_DESCRIPTION="Diese Tour zeigt, wie man eine geführte Tour für das Backend erstellen kann."
```suggestion
COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_DESCRIPTION="Diese Tour zeigt, wie man eine geführte Tour für das Backend erstellt."
```

2023-04-17 14:59 UTC, zero-24 commented on administrator/language/de-DE/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_TITLE_DESCRIPTION="Einen Titel für die gewünschte Tour eingeben."
```suggestion
COM_GUIDEDTOURS_TOUR_GUIDEDTOURS_STEP_TITLE_DESCRIPTION="Einen Titel für die Tour eingeben."
```

2023-04-17 14:59 UTC, zero-24 commented on administrator/language/de-DE/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_DESCRIPTION="Diese Tour zeigt, wie man einen Schritt für eine geführte Tour erstellen kann."
```suggestion
COM_GUIDEDTOURS_TOUR_GUIDEDTOURSTEPS_DESCRIPTION="Diese Tour zeigt, wie man einen Schritt für eine geführte Tour hinzufügt."
```

2023-04-17 14:59 UTC, zero-24 commented on administrator/language/de-DE/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_ARTICLES_STEP_FEATURED_DESCRIPTION="Haupteintrag 'Ja' wählen, um den Beitrag zu kennzeichnen. Dies kann z.&#8239;B. für Sortierungen verwendet werden."
```suggestion
COM_GUIDEDTOURS_TOUR_ARTICLES_STEP_FEATURED_DESCRIPTION="'Ja' wählen, um den Beitrag als Haupteintrag zu kennzeichnen. Dies kann z.&#8239;B. für Sortierungen verwendet werden."
```

2023-04-17 14:59 UTC, zero-24 commented on administrator/language/de-DE/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_MENUS_STEP_UNIQUENAME_TITLE="Einen eindeutigen Namen hinzufügen"
```suggestion
COM_GUIDEDTOURS_TOUR_MENUS_STEP_UNIQUENAME_TITLE="Einen eindeutigen Namen eingeben"
```

2023-04-17 14:59 UTC, zero-24 commented on administrator/language/de-DE/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_FEATURED_DESCRIPTION="Haupteintrag 'Ja' wählen, um den Kontakt zu kennzeichnen. Dies kann z.&#8239;B. für Sortierungen verwendet werden."
```suggestion
COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_FEATURED_DESCRIPTION="'Ja' wählen, um den Kontakt als Haupteintrag zu kennzeichnen. Dies kann z.&#8239;B. für Sortierungen verwendet werden."
```

2023-04-17 14:59 UTC, zero-24 commented on administrator/language/de-DE/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_USERS_STEP_SYSTEMEMAIL_DESCRIPTION="Diese Option auf ja setzen, wenn der Benutzer System-E-Mails erhalten soll."
```suggestion
COM_GUIDEDTOURS_TOUR_USERS_STEP_SYSTEMEMAIL_DESCRIPTION="Diese Option auf 'Ja' setzen, wenn der Benutzer System-E-Mails erhalten soll."
```

2023-04-17 14:59 UTC, zero-24 commented on administrator/language/de-DE/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_USERS_STEP_PASSWORDRESET_DESCRIPTION="Wenn diese Option auf ja gesetzt ist, muss der Benutzer sein Passwort bei der nächsten Anmeldung auf der Website zurücksetzen."
```suggestion
COM_GUIDEDTOURS_TOUR_USERS_STEP_PASSWORDRESET_DESCRIPTION="Wenn diese Option auf 'Ja' gesetzt ist, muss der Benutzer sein Passwort bei der nächsten Anmeldung auf der Website zurücksetzen."
```

2023-04-17 17:16 UTC, heelc29 commented on administrator/language/de-DE/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOURS_VIEW_DEFAULT_DESC="Zeigt eine Liste aller geführten Touren."
```suggestion
COM_GUIDEDTOURS_TOURS_VIEW_DEFAULT_TITLE="Alle geführten Touren auflisten"
COM_GUIDEDTOURS_TOURS_VIEW_DEFAULT_DESC="Zeigt eine Liste aller geführten Touren an."
```
s. #2718
![image](https://user-images.githubusercontent.com/66922325/232560471-88a99787-fced-4a87-95c4-ddf70d7937ae.png)

2023-04-17 17:23 UTC, heelc29 commented on administrator/language/de-DE/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_SAVECLOSE_DESCRIPTION="Konakt speichern und schließen."
```suggestion
COM_GUIDEDTOURS_TOUR_CONTACTS_STEP_SAVECLOSE_DESCRIPTION="Kontakt speichern und schließen."
```

2023-04-17 17:23 UTC, heelc29 commented on administrator/language/de-DE/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_NEWSFEEDS_STEP_NEW_DESCRIPTION="Schaltfläche 'Neu' auswählen, um einen neuen Newfeed zu erstellen."
```suggestion
COM_GUIDEDTOURS_TOUR_NEWSFEEDS_STEP_NEW_DESCRIPTION="Schaltfläche 'Neu' auswählen, um einen neuen Newsfeed zu erstellen."
```

2023-04-17 17:23 UTC, heelc29 commented on administrator/language/de-DE/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_CATEGORIES_STEP_TAGS_DESCRIPTION="Schlagwörter (Tags) für die Kategorie auswählen. Es kann auch direkt eine neues Schlagwort angelegt werden, indem man den Namen in das Feld eing
```suggestion
COM_GUIDEDTOURS_TOUR_CATEGORIES_STEP_TAGS_DESCRIPTION="Schlagwörter (Tags) für die Kategorie auswählen. Es kann auch direkt ein neues Schlagwort angelegt werden, indem man den Namen in das Feld eingibt und mit der Eingabetaste bestätigt."
```

2023-04-17 17:23 UTC, heelc29 commented on administrator/language/de-DE/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_MENUS_STEP_NEW_DESCRIPTION="Schaltfläche 'Neu' wählen, um eine neues Menü zu erstellen."
```suggestion
COM_GUIDEDTOURS_TOUR_MENUS_STEP_NEW_DESCRIPTION="Schaltfläche 'Neu' wählen, um ein neues Menü zu erstellen."
```

2023-04-17 17:29 UTC, heelc29 commented on administrator/language/de-DE/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_MENUS_DESCRIPTION="Diese Tour zeigt, wie man ein Menü erstellen können."
```suggestion
COM_GUIDEDTOURS_TOUR_MENUS_DESCRIPTION="Diese Tour zeigt, wie man ein Menü erstellen kann."
```

2023-04-17 17:29 UTC, heelc29 commented on administrator/language/de-DE/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_BANNERS_DESCRIPTION="Diese Tour zeigt, wie man ein Banner erstellen kann."
```suggestion
COM_GUIDEDTOURS_TOUR_BANNERS_DESCRIPTION="Diese Tour zeigt, wie man einen Banner erstellen kann."
```

2023-04-17 17:30 UTC, tecpromotion approved these changes, later dismissed
Thanks

2023-04-17 17:30 UTC, tecpromotion commented on administrator/language/de-DE/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_BANNERS_DESCRIPTION="Diese Tour zeigt, wie man ein Banner erstellen kann."
```suggestion
COM_GUIDEDTOURS_TOUR_BANNERS_DESCRIPTION="Diese Tour zeigt, wie man einen Banner erstellt."
```

2023-04-17 17:31 UTC, tecpromotion commented on administrator/language/de-DE/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_MENUS_DESCRIPTION="Diese Tour zeigt, wie man ein Menü erstellen können."
```suggestion
COM_GUIDEDTOURS_TOUR_MENUS_DESCRIPTION="Diese Tour zeigt, wie man ein Menü erstellt."
```

2023-04-17 17:59 UTC, heelc29 commented on administrator/language/de-DE/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_USERS_DESCRIPTION="Diese Tour zeigt, wie man einen Benutzer anlegen kann."
```suggestion
COM_GUIDEDTOURS_TOUR_USERS_DESCRIPTION="Diese Tour zeigt, wie man einen Benutzer anlegt."
```

2023-04-17 18:00 UTC, heelc29 commented on administrator/language/de-DE/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_USERS_DESCRIPTION="Diese Tour zeigt, wie man einen Benutzer anlegen kann."
oder `erstellt`?

2023-04-17 18:09 UTC, heelc29 commented on administrator/language/de-DE/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_ARTICLES_STEP_TAGS_TITLE="Schlagwörter wählen"
```suggestion
COM_GUIDEDTOURS_TOUR_ARTICLES_STEP_TAGS_TITLE="Schlagwörter hinzufügen"
```
wird bereits 3x verwendet

2023-04-17 18:09 UTC, heelc29 commented on administrator/language/de-DE/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_USERS_STEP_SAVECLOSE_DESCRIPTION="Den Benutzer speichern und schließen."
```suggestion
COM_GUIDEDTOURS_TOUR_USERS_STEP_SAVECLOSE_DESCRIPTION="Benutzer speichern und schließen."
```

2023-04-17 18:09 UTC, heelc29 commented on administrator/language/de-DE/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_MENUS_STEP_CONGRATULATIONS_DESCRIPTION="Ein Menü wurde erstellt."
```suggestion
COM_GUIDEDTOURS_TOUR_MENUS_STEP_CONGRATULATIONS_DESCRIPTION="Ein neues Menü wurde erstellt."
```

2023-04-17 18:28 UTC, heelc29 commented on administrator/language/de-DE/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_BANNERS_STEP_CONGRATULATIONS_DESCRIPTION="Ein neues Banner wurde erstellt"
```suggestion
COM_GUIDEDTOURS_TOUR_BANNERS_STEP_CONGRATULATIONS_DESCRIPTION="Ein neues Banner wurde erstellt."
```
Fehlt im Core. Sollen wir den ergänzen und dann noch einen PR für den Core erstellen?

2023-04-17 18:35 UTC, heelc29 commented
Wäre sonst mal "zufrieden" damit. Das einzige wäre evtl. noch mit `gewünschten/erforderlichen Titel` ...

2023-04-17 18:39 UTC, zero-24 commented on administrator/language/de-DE/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_BANNERS_STEP_CONGRATULATIONS_DESCRIPTION="Ein neues Banner wurde erstellt"
Ja

2023-04-17 18:54 UTC, heelc29 commented on administrator/language/de-DE/com_guidedtours.sys.ini
> +COM_GUIDEDTOURS_TOUR_BANNERS_STEP_CONGRATULATIONS_DESCRIPTION="Ein neues Banner wurde erstellt"
https://github.com/joomla/joomla-cms/pull/40401

2023-04-17 18:59 UTC, zero-24 approved these changes
Ok dann mergen wir das hier jetzt als ersten Stand. Danke euch :)

2023-04-17 18:59 UTC, merged