[5.0] %d not %s for integer in sprintf
joomlagerman/joomla pull request #2993
Opened 2023-09-13 11:28 UTC by tecpromotion

Pull Request für Issue #2983 .

### Zusammenfassung der Änderungen

%d not %s for integer in sprintf

### Wo wird der Sprachstring angezeigt / Wie kann getestet werden

backend
frontend

2023-09-13 13:22 UTC, heelc29 commented on language/de-DE/finder_cli.ini
> +FINDER_CLI_BATCH_PAUSING=" * Pausieren der Verarbeitung für %d Sekunden &hellip;"
Sollten das `&hellip;` nicht auch wieder zu `...` geändert werden, da die CLI kein HTML anzeigen kann

![image](https://github.com/joomlagerman/joomla/assets/66922325/1980738f-663d-4593-a608-013e3dfbf6c5)

2023-09-13 13:24 UTC, tecpromotion commented on language/de-DE/finder_cli.ini
> +FINDER_CLI_BATCH_PAUSING=" * Pausieren der Verarbeitung für %d Sekunden &hellip;"
Macht absolut Sinn.

2023-09-13 14:14 UTC, heelc29 requested changes
siehe https://github.com/joomla/joomla-cms/pull/41740

2023-09-13 14:14 UTC, heelc29 commented on language/de-DE/finder_cli.ini
> +FINDER_CLI_SKIPPING_PAUSE_LOW_BATCH_PROCESSING_TIME=" * Pause überspringen, da der vorherige Stapel eine sehr geringe Verarbeitungszeit hatte (%ds < %ds)."
```suggestion
FINDER_CLI_SKIPPING_PAUSE_LOW_BATCH_PROCESSING_TIME=" * Pause überspringen, da der vorherige Stapel eine sehr geringe Verarbeitungszeit hatte (%ss < %ds)."
```

2023-09-13 14:14 UTC, heelc29 commented on administrator/language/de-DE/com_finder.ini
> +COM_FINDER_STATISTICS_STATS_DESCRIPTION="Der indexierte Inhalt dieser Seite enthält %d Ausdrücke aus %d Links mit %d Attributen in %d Inhaltsgruppen."
```suggestion
COM_FINDER_STATISTICS_STATS_DESCRIPTION="Der indexierte Inhalt dieser Seite enthält %s Ausdrücke aus %s Links mit %s Attributen in %s Inhaltsgruppen."
```

2023-09-13 14:14 UTC, heelc29 commented on administrator/language/de-DE/plg_content_vote.ini
> +PLG_VOTE_STAR_RATING="Bewertung: %d von 5"
```suggestion
PLG_VOTE_STAR_RATING="Bewertung: %s von 5"
```

2023-09-13 14:34 UTC, tecpromotion commented on language/de-DE/finder_cli.ini
> +FINDER_CLI_SKIPPING_PAUSE_LOW_BATCH_PROCESSING_TIME=" * Pause überspringen, da der vorherige Stapel eine sehr geringe Verarbeitungszeit hatte (%ds < %ds)."
siehe https://github.com/joomla/joomla-cms/pull/41742

2023-09-14 08:42 UTC, tecpromotion commented
RTC

2023-09-15 08:31 UTC, heelc29 approved these changes
![image](https://github.com/joomlagerman/joomla/assets/66922325/bc400c02-35ae-4236-9b98-a2bf2bc4183e)
![image](https://github.com/joomlagerman/joomla/assets/66922325/98f02598-9d8c-4828-bf66-c5d47800f00a)
![image](https://github.com/joomlagerman/joomla/assets/66922325/c85ac6a1-8149-48ad-8c43-46a67f9b0c40)
![image](https://github.com/joomlagerman/joomla/assets/66922325/e1251e37-fcaa-4637-8092-358753038405)
![image](https://github.com/joomlagerman/joomla/assets/66922325/fb782434-1225-450e-b6fe-6f91c952fed9)
![image](https://github.com/joomlagerman/joomla/assets/66922325/aae3c4c0-dbaf-4856-a7ec-26cfdb34ea12)
![image](https://github.com/joomlagerman/joomla/assets/66922325/1c76ef14-65b9-4dfc-a4e4-d2925d9e4770)
![image](https://github.com/joomlagerman/joomla/assets/66922325/e0ffa141-0a2f-44af-81b3-f60ca582e045)
![image](https://github.com/joomlagerman/joomla/assets/66922325/d7fc0422-d539-437c-9340-06f1ad03a146)
![image](https://github.com/joomlagerman/joomla/assets/66922325/f11b4edc-d5be-45a0-9cf9-81a710217113)
![image](https://github.com/joomlagerman/joomla/assets/66922325/af6abe56-5e3f-4a1a-949d-4a782e75f190)

2023-09-15 08:31 UTC, merged

2023-09-15 08:31 UTC, heelc29 commented
Danke