[5.3] [com_scheduler] task execution history view
joomlagerman/joomla pull request #3351
Opened 2024-12-12 08:47 UTC by tecpromotion

Pull Request für Issue #3350 .

### Zusammenfassung der Änderungen

- [ ] add new strings
- [ ] translation

### Wo wird der Sprachstring angezeigt / Wie kann getestet werden

backend

2024-12-14 16:11 UTC, zero-24 commented
@tecpromotion die strings sind noch nicht übersetzt?

2025-02-16 18:10 UTC, heelc29 requested changes

2025-02-16 18:10 UTC, heelc29 commented on administrator/language/de-DE/com_scheduler.ini
> +COM_SCHEDULER_CLEAR_FAIL="Aufgabenprotokolle konnten nicht gelöscht werden."
```suggestion
COM_SCHEDULER_CLEAR_FAIL="Ausführungsprotokolle konnten nicht gelöscht werden."
```
einheitlich

2025-02-16 18:10 UTC, heelc29 commented on administrator/language/de-DE/com_scheduler.ini
> +COM_SCHEDULER_TASK_TIMES_DESC="Zeiten absteigend"
Times = x Mal

2025-02-16 18:10 UTC, heelc29 commented on administrator/language/de-DE/com_scheduler.ini
> +COM_SCHEDULER_TASK_RESUME="Will Resume: %s"
Übersetzung?

2025-02-16 20:14 UTC, zero-24 requested changes

2025-02-16 20:14 UTC, zero-24 commented on administrator/language/de-DE/com_scheduler.ini
> +COM_SCHEDULER_TOOLBAR_PURGE_CONFIRM="Sicher, dass der gesamte Ausführungsverlauf gelöscht werden soll?"
```suggestion
COM_SCHEDULER_TOOLBAR_PURGE_CONFIRM="Sind Sie sicher, dass der gesamte Ausführungsverlauf gelöscht werden soll?"
```

2025-02-16 20:14 UTC, zero-24 commented on administrator/language/de-DE/com_scheduler.ini
> +COM_SCHEDULER_TOOLBAR_PURGE="Verlauf löschen"
```suggestion
COM_SCHEDULER_TOOLBAR_PURGE="Ausführungsverlauf löschen"
```

2025-02-16 20:15 UTC, tecpromotion commented on administrator/language/de-DE/com_scheduler.ini
> +COM_SCHEDULER_TOOLBAR_PURGE_CONFIRM="Sicher, dass der gesamte Ausführungsverlauf gelöscht werden soll?"
Wollte "Sie" vermeiden.

2025-02-16 20:17 UTC, tecpromotion commented on administrator/language/de-DE/com_scheduler.ini
> +COM_SCHEDULER_TOOLBAR_PURGE="Verlauf löschen"
Ist dann sehr lang.
Und aus der Überschrift wird eigentlich klar, dass es der Verlauf ist:
![Bildschirmfoto 2025-02-16 um 21 16 14](https://github.com/user-attachments/assets/3c56416b-aca0-45a2-afd1-e945a2d8528a)

2025-02-16 20:31 UTC, tecpromotion commented on administrator/language/de-DE/com_scheduler.ini
> +COM_SCHEDULER_TOOLBAR_PURGE_CONFIRM="Sicher, dass der gesamte Ausführungsverlauf gelöscht werden soll?"
@zero-24 verwenden wir sonst auch so in anderen Fällen.

2025-02-16 20:31 UTC, zero-24 commented on administrator/language/de-DE/com_scheduler.ini
> +COM_SCHEDULER_TOOLBAR_PURGE="Verlauf löschen"
OK :)

2025-02-16 20:31 UTC, zero-24 commented on administrator/language/de-DE/com_scheduler.ini
> +COM_SCHEDULER_TOOLBAR_PURGE_CONFIRM="Sicher, dass der gesamte Ausführungsverlauf gelöscht werden soll?"
Fine for me.

2025-02-16 20:31 UTC, zero-24 approved these changes

2025-02-16 20:32 UTC, merged

2025-02-16 20:32 UTC, zero-24 commented
Merging thanks