[WIP] [4.0] add 6 new administrator/language/com_files
joomlagerman/joomla pull request #858
Opened 2019-12-28 08:20 UTC by tecpromotion

Pull Request für Issue #804 

### Zusammenfassung der Änderungen

add 6 new files, change to german header

translation still WIP

com_csp.ini
com_csp.sys.ini
com_mails.ini
com_mails.sys.ini
com_workflow.ini
com_workflow.sys.ini

### Wo wird der Sprachstring angezeigt / Wie kann getestet werden

Backend

2020-10-01 08:51 UTC, tecpromotion commented
@max123kl Wenn du magst, schau dir diesen PR doch mal an.
Hier sind die 6 Dateien zu übersetzen.

2020-10-01 11:08 UTC, max123kl commented
Wie vermeiden wir, dass gleichzeitig an denselben Dateien gearbeitet wird?
Fall kein Einwand besteht, würde ich zuerst mit com_csp.ini anfangen.

Gibt es eine Möglichkeit meine Anpassungen dann in diesem PR einzufügen oder sollte ich dafür einen neuen starten?

2020-10-01 11:11 UTC, tecpromotion commented
@max123kl du müsstest einfach in https://github.com/tecpromotion/joomla/tree/804-add-new-files pushen.
Vermeidung durch Absprache. Sprich diesen PR kannst du machen.

2020-10-01 12:46 UTC, max123kl commented
Ich habe mir deinen "804-add-new-files" Branch als Remote hier angelegt.
Ein PR dorthin sollte also funktionieren.
BTW:
Im Vergleich zu deiner Version der `com_csp.ini` gibt es in der aktuellen Core-Version Abweichungen.
Wie sollten solche Abweichungen behandelt werden, um auch den Verlauf konsistent zu halten?

2020-10-01 12:51 UTC, tecpromotion commented
Mein Stand ist ja aus Dezember 19.
Dieser diente damals lediglich als Hilfsmitteln.

Ziel ist natürlich den Stand Core von heute abzubilden.

2020-10-01 12:53 UTC, max123kl commented
Das heißt wir müssen nicht jeden Commit im Core hier nachvollziehen können, richtig?

2020-10-01 12:56 UTC, tecpromotion commented
Das wäre Wunsch aber ist nicht realisierbar. Schon gar nicht mit den ganzen offenen Issues derzeit.

Heißt am Beispiel hier, dass sich einige offene Issues einfach schließen lassen weil sie dann faktisch schon bearbeitet wurden, wenn man den Stand heute von den 6 Dateien einpflegt.

Wenn wir diese offenen PRs hier mal haben, dann kann man die offenen Issues sehr leicht und wahrscheinlich sehr schnell abarbeiten.

2020-10-01 13:07 UTC, max123kl commented
OK, dann pflege ich in den von mir bearbeiteten Dateien die jeweilige aktuelle Core-Revision mit ein und vermerke (wie beim letzten PR #1254) in den Commit-Messages den referenzierenden Commit.

2020-10-01 13:15 UTC, tecpromotion commented
Wie ich vorgehen würde am Beispiel der com_csp.ini

Step 1: Inhalt von https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/language/en-GB/com_csp.ini in die hier hinterlegte. com_csp.ini einfügen.
Step 2: übersetzen.

Da hier noch keinerlei Übersetzungen gemacht wurden, einfach drüber. Referenzierung ist hier nice to have.

Ich kann die auch fix drüber kopieren und du machst die Übersetzung @max123kl ?

2020-10-01 13:18 UTC, max123kl commented
Bei der kleinen Datei ist das nicht mehr notwendig – aber die anderen 5 könnten (falls notwendig) aktualisiert werden.

2020-10-01 13:19 UTC, tecpromotion commented
> Bei der kleinen Datei ist das nicht mehr notwendig – aber die anderen 5 könnten (falls notwendig) aktualisiert werden.

Schon angefangen?
Sonst mach ich das schnell für die 6... ist ja kein Aufwand.

2020-10-01 13:24 UTC, max123kl commented
Ja, da ich ab morgen, bis vermutlich Dienstag, nicht dazu kommen werde.

2020-10-01 13:26 UTC, tecpromotion commented
> Ja, da ich ab morgen, bis vermutlich Dienstag, nicht dazu kommen werde.

Ok, die Dateien sind nun aber auch von den Strings und der Sortierung sauber neu hochgeladen. Machst einfach Pull.
Und kopierst dir die Übersetzungen kurz temp. in eine txt.

2020-10-06 06:26 UTC, max123kl commented
Ich habe gerade für die beiden ersten übersetzten Dateien einen PR ausgelöst.
Da ich vorher den Branch 4.0-dev in den 804er gemergt hatte, kommen die anderen Commits leider auch mit.
Bitte die Commit-Message zu `c9a14e2` beachten.

2020-10-06 07:12 UTC, tecpromotion commented
> Ich habe gerade für die beiden ersten übersetzten Dateien einen PR ausgelöst.
> Da ich vorher den Branch 4.0-dev in den 804er gemergt hatte, kommen die anderen Commits leider auch mit und verursachen vermutlich den Fehler.
> Kann ich den Merge irgendwie zurücknehmen?
> 
> Bitte die Commit-Message zu `c9a14e2` beachten.

Bisher kein PR oder commit angekommen.
Eigentlich musst du nur in diesen PR pushen und immer drauf achten, dass du regelmässig pullst.

2020-10-06 07:14 UTC, tecpromotion commented
Ah, du hast in meinen Branch einen PR gemacht. I see.

2020-10-06 07:18 UTC, tecpromotion commented
@max123kl ich habe die beiden Dateien von dir mal hier reingezogen.

2020-10-06 07:28 UTC, max123kl commented
Sorry, bin eigentlich Designer und hier immer noch "Learning by Doing"
BTW die anderen Dateien sind in Arbeit

2020-10-06 10:42 UTC, zero-24 commented
> Sorry, bin eigentlich Designer und hier immer noch "Learning by Doing"
> BTW die anderen Dateien sind in Arbeit

Kein Thema so war es richtig wenn du Fragen hast immer melden dann kann ich dir gerne helfen. Aber so wie du es gemacht hast war es schon richtig :+1:

2020-10-06 11:25 UTC, max123kl commented
Da ich parallel für JDOC lokalisierte Screenshots erstellen will, habe ich mir hier lokal eine J4-beta eingerichtet.
Für die 4 restlichen Dateien in diesem PR hier, finde ich die zugehörigen Screens nicht, um die Strings kontextbezogen und logisch zu übersetzen.
z.B. die `com_mails.ini` enthält den String `COM_MAILS_FIELD_MAIL_REPLY_TO_NAME_LABEL="Reply To Name"` und wird in der Datei `/administrator/components/com_mails/forms/template.xml`, Zeile 138ff benutzt.
Ich glaube, dass die Zeile `showon="alternative_mailconfig:1` den Screen definiert. Wie finde ich den?

2020-10-06 13:45 UTC, max123kl commented
@tecpromotion @zero-24 
die 4 restlichen Dateien wären fertig - müssten aber reviewed werden.
Ich habe sie in meinem Repo und auch lokal im Branch `804-update`

Kann ich so nach https://github.com/tecpromotion/joomla/tree/804-add-new-files pushen?
`git push --repo https://github.com/tecpromotion/joomla/tree/804-add-new-files`

2020-10-06 13:50 UTC, zero-24 commented
Du müsstest die in deinen fork pushen und dann einen PR für Stefans branch machen

2020-10-06 14:05 UTC, max123kl commented
Ist mir klar, aber als ich das genau so mit den beiden ersten Files gemacht hatte, war Stefan überrascht, dass ich auf seinen Fork einen PR gemacht hatte. Deshalb die Nachfrage

2020-10-06 14:19 UTC, tecpromotion commented
> Ist mir klar, aber als ich das genau so mit den beiden ersten Files gemacht hatte, war Stefan überrascht, dass ich auf seinen Fork einen PR gemacht hatte. Deshalb die Nachfrage

Ganz so war es nicht :)
Du musst aufpassen, dass du immer aktuell bist, so dass nur Files gepushed werden, welche auch relevant sind.

2020-10-06 14:33 UTC, max123kl commented
Ja, das war mein Fehler.

2020-10-06 18:37 UTC, zero-24 commented on administrator/language/de-DE/com_csp.ini
> +COM_CSP="Inhalt-Sicherheitsrichtlinie"
hmm spricht etwas auch eurer sich dagegen den Technischennamen "Content Security Policy" zu benutzen? Alles an Dokumentation was man zu dem Thema findet nennt es "Content Security Policy" und ich bin mir nicht sicher ob wir uns einen gefallen tun das zu übersetzen.

2020-10-06 18:40 UTC, zero-24 commented on administrator/language/de-DE/com_mails.ini
> +COM_MAILS_CONFIG_FIELD_COPY_MAILS_LABEL="Kopie zusenden"
```suggestion
COM_MAILS_CONFIG_FIELD_COPY_MAILS_LABEL="Kopie senden"
```

2020-10-06 18:41 UTC, zero-24 commented on administrator/language/de-DE/com_csp.ini
> +COM_CSP="Inhalt-Sicherheitsrichtlinie"
Dann würde ich suggestions dafür einreichen

2020-10-06 18:45 UTC, tecpromotion commented on administrator/language/de-DE/com_csp.ini
> +COM_CSP="Inhalt-Sicherheitsrichtlinie"
Ja bitte CSP verwenden @zero-24

2020-10-06 19:40 UTC, zero-24 requested changes

2020-10-06 19:40 UTC, zero-24 commented on administrator/language/de-DE/com_csp.ini
> +COM_CSP_AUTO_UNSAFE_INLINE_WARNING="Es ist eine Regel konfiguriert, die nach wie vor 'unsafe-inline' zulässt, welche die Inhalt-Sicherheitsrichtlinie umgeht. Sie erlaubt die Ausführung von unsicheren
```suggestion
COM_CSP_AUTO_UNSAFE_INLINE_WARNING="Es ist eine Regel konfiguriert, die nach wie vor 'unsafe-inline' zulässt, welche die Content-Security-Policy umgeht. Sie erlaubt die Ausführung von unsicheren In-Page-Skripten und Event-Handlern."
```

2020-10-06 19:40 UTC, zero-24 commented on administrator/language/de-DE/com_csp.ini
> +COM_CSP_COLLECTING_TRASH_WARNING="Die Inhalt-Sicherheitsrichtlinie ist im Erkennungsmodus. Objekte, die im Papierkorb abgelegt wurden, werden erst dann wieder gefunden, wenn sie aus dem Papierkorb he
```suggestion
COM_CSP_COLLECTING_TRASH_WARNING="Die Content-Security-Policy ist im Erkennungsmodus. Reports, welche im Papierkorb sind werden hier nicht erneut angezeigt. Bitte den Papierkorb leeren."
```

2020-10-06 19:40 UTC, zero-24 commented on administrator/language/de-DE/com_csp.ini
> +COM_CSP_CONFIGURATION="Inhalt-Sicherheitsrichtlinie: Optionen"
```suggestion
COM_CSP_CONFIGURATION="Content-Security-Policy: Optionen"
```

2020-10-06 19:40 UTC, zero-24 commented on administrator/language/de-DE/com_csp.ini
> +COM_CSP_CONTENTSECURITYPOLICY_FRAME_ANCESTORS_SELF_ENABLED_DESC="Den CSP-Klickjacking-Schutz für Frame-Vorgänger aktivieren und nur den Ursprung 'self' zulassen. UM andere Quellen als 'self' zu erlau
```suggestion
COM_CSP_CONTENTSECURITYPOLICY_FRAME_ANCESTORS_SELF_ENABLED_DESC="Den Content-Security-Policy-Klickjacking-Schutz (frame-ancestors self) aktivieren. Für eine detaillierte Konfiguration bitte das untenstehende Formular benutzen."
```

2020-10-06 19:40 UTC, zero-24 commented on administrator/language/de-DE/com_csp.ini
> +COM_CSP_CONTENTSECURITYPOLICY_MODE_DETECT="Erkennen"
```suggestion
COM_CSP_CONTENTSECURITYPOLICY_MODE_DETECT="Sammeln"
```

2020-10-06 19:40 UTC, zero-24 commented on administrator/language/de-DE/com_csp.ini
> +COM_CSP_CONTENTSECURITYPOLICY_MODE_CUSTOM="Angepasst"
```suggestion
COM_CSP_CONTENTSECURITYPOLICY_MODE_CUSTOM="Benutzerdefiniert"
```

2020-10-06 19:40 UTC, zero-24 commented on administrator/language/de-DE/com_csp.ini
> +COM_CSP_CONTENTSECURITYPOLICY="<a href='https://scotthelme.co.uk/content-security-policy-an-introduction' target='_blank' rel='noopener noreferrer'>Content Security Policy (CSP)</a>"
```suggestion
COM_CSP_CONTENTSECURITYPOLICY="<a href='https://scotthelme.co.uk/content-security-policy-an-introduction' target='_blank' rel='noopener noreferrer'>Content-Security-Policy</a>"
```

2020-10-06 19:40 UTC, zero-24 commented on administrator/language/de-DE/com_csp.ini
> +COM_CSP_CONTENTSECURITYPOLICY_NONCE_ENABLED_DESC="Die Whitelist für bestimmte Inline-Skripte aktivieren, unter Verwendung einer kryptografischen Nonce (einmalig verwendeter Zahl) für alle Skripte und
```suggestion
COM_CSP_CONTENTSECURITYPOLICY_NONCE_ENABLED_DESC="Einen kryptografische Nonce für alle inline-skripte und inline-styles generieren, welche über die Joomla-API in die Seite geladen werden, und mittels Content-Security-Policy freigeben. Die Angabe der Nonce führt dazu, dass ein moderner Browser 'unsafe-inline' ignoriert."
```

2020-10-06 19:40 UTC, zero-24 commented on administrator/language/de-DE/com_csp.ini
> +COM_CSP_CONTENTSECURITYPOLICY_SCRIPT_HASHES_ENABLED="<a href='https://scotthelme.co.uk/content-security-policy-an-introduction/#hash' target='_blank' rel='noopener noreferrer'>Script hashes</a>"
```suggestion
COM_CSP_CONTENTSECURITYPOLICY_SCRIPT_HASHES_ENABLED="<a href='https://scotthelme.co.uk/content-security-policy-an-introduction/#hash' target='_blank' rel='noopener noreferrer'>Skript-Hashes</a>"
```

2020-10-06 19:40 UTC, zero-24 commented on administrator/language/de-DE/com_csp.ini
> +COM_CSP_CONTENTSECURITYPOLICY_SCRIPT_HASHES_ENABLED_DESC="Die optionalen hashbasierten Whitelist-Inline-Skripte aktivieren, die einen kryptografischen Hash für alle Skripte verwenden, welche die Joom
```suggestion
COM_CSP_CONTENTSECURITYPOLICY_SCRIPT_HASHES_ENABLED_DESC="Einen kryptografischen Hash für alle inline-skripte generieren, welche über die Joomla-API in die Seite geladen werden, und mittels Content-Security-Policy freigeben. Die Angabe von Hashes führt dazu, dass ein moderner Browser 'unsafe-inline' ignoriert."
```

2020-10-06 19:40 UTC, zero-24 commented on administrator/language/de-DE/com_csp.ini
> +COM_CSP_CONTENTSECURITYPOLICY_STYLE_HASHES_ENABLED="<a href='https://scotthelme.co.uk/content-security-policy-an-introduction/#hash' target='_blank' rel='noopener noreferrer'>Style hashes</a>"
```suggestion
COM_CSP_CONTENTSECURITYPOLICY_STYLE_HASHES_ENABLED="<a href='https://scotthelme.co.uk/content-security-policy-an-introduction/#hash' target='_blank' rel='noopener noreferrer'>Style-Hashes</a>"
```

2020-10-06 19:40 UTC, zero-24 commented on administrator/language/de-DE/com_csp.ini
> +COM_CSP_CONTENTSECURITYPOLICY_STYLE_HASHES_ENABLED_DESC="Die optionalen hashbasierten Whitelist-Inline-Stile aktivieren, die einen kryptografischen Hash für alle Stile benutzen, welche die Joomla-API
```suggestion
COM_CSP_CONTENTSECURITYPOLICY_STYLE_HASHES_ENABLED_DESC="Einen kryptografischen Hash für alle inline-styles generieren, welche über die Joomla-API in die Seite geladen werden, und mittels Content-Security-Policy freigeben. Die Angabe von Hashes führt dazu, dass ein moderner Browser 'unsafe-inline' ignoriert.""
```

2020-10-06 19:40 UTC, zero-24 commented on administrator/language/de-DE/com_csp.ini
> +COM_CSP_FILTER_SEARCH_LABEL="Berichte der Inhalt-Sicherheitsrichtlinie durchsuchen"
```suggestion
COM_CSP_FILTER_SEARCH_LABEL="Berichte der Content-Security-Policy durchsuchen"
```

2020-10-06 19:40 UTC, zero-24 commented on administrator/language/de-DE/com_csp.ini
> +COM_CSP_HEADING_CLIENT_ASC="Standort, aufsteigend"
```suggestion
COM_CSP_HEADING_CLIENT_ASC="Client, aufsteigend"
```

2020-10-06 19:40 UTC, zero-24 commented on administrator/language/de-DE/com_csp.ini
> +COM_CSP_HEADING_CLIENT_DESC="Standort, absteigend"
```suggestion
COM_CSP_HEADING_CLIENT_DESC="Client, absteigend"
```

2020-10-06 19:40 UTC, zero-24 commented on administrator/language/de-DE/com_csp.ini
> +COM_CSP_REPORTS="Inhalt-Sicherheitsrichtlinie Berichtr"
```suggestion
COM_CSP_REPORTS="Content-Security-Policy Berichte"
```

2020-10-06 19:40 UTC, zero-24 commented on administrator/language/de-DE/com_csp.ini
> +COM_CSP_TABLE_CAPTION="Inhaltsverzeichnis der Berichte zur Inhalt-Sicherheitsrichtlinie"
```suggestion
COM_CSP_TABLE_CAPTION="Tabelle der gesammelten Content-Security-Policy Berichte"
```

2020-10-06 19:40 UTC, zero-24 commented on administrator/language/de-DE/com_csp.sys.ini
> +COM_CSP="Content Security Policy"
```suggestion
COM_CSP="der Content-Security-Policy"
```

2020-10-06 19:40 UTC, zero-24 commented on administrator/language/de-DE/com_csp.sys.ini
> +COM_CSP_REPORTS_VIEW_DEFAULT_DESC="Eine Liste aller CSP-Berichte anzeigen."
```suggestion
COM_CSP_REPORTS_VIEW_DEFAULT_DESC="Eine Liste aller Content-Security-Policy-Berichte anzeigen."
```

2020-10-06 19:40 UTC, zero-24 commented on administrator/language/de-DE/com_csp.sys.ini
> +COM_CSP_REPORTS_VIEW_DEFAULT_TITLE="Alle Berichte zur Inhalt-Sicherheitsrichtlinie (CSP) anzeigen."
```suggestion
COM_CSP_REPORTS_VIEW_DEFAULT_TITLE="Alle Content-Security-Policy Berichte anzeigen."
```

2020-10-06 19:40 UTC, zero-24 commented on administrator/language/de-DE/com_csp.sys.ini
> +COM_CSP_XML_DESCRIPTION="Diese Komponente verwaltet die Berichte zur Inhalt-Sicherheitsrichtlinie (CSP)."
```suggestion
COM_CSP_XML_DESCRIPTION="Diese Komponente verwaltet die gesammelten Berichte und wird zur Konfiguration der Content-Security-Policy genutzt."
```

2020-10-06 22:19 UTC, max123kl commented on administrator/language/de-DE/com_csp.ini
> +COM_CSP="Inhalt-Sicherheitsrichtlinie"
OK, finde ich auch besser nicht alles zwangsweise eindeutschen zu müssen

2020-10-07 06:12 UTC, paternax commented
joomla/administrator/language/de-DE/com_workflow.ini

Zur Zeit: COM_WORKFLOW_BASIC_WORKFLOW="Grundsätzlicher Workflow" 
Vorschlag: Basis-Workflow wäre kürzer und eingänglicher.

2020-10-07 10:00 UTC, tecpromotion commented on administrator/language/de-DE/com_csp.sys.ini
> +COM_CSP="Content Security Policy"
> der @zero-24?

```suggestion
COM_CSP="Content-Security-Policy"
```

2020-10-07 10:00 UTC, tecpromotion commented
> joomla/administrator/language/de-DE/com_workflow.ini
> 
> Zur Zeit: COM_WORKFLOW_BASIC_WORKFLOW="Grundsätzlicher Workflow"
> Vorschlag: Basis-Workflow wäre kürzer und eingänglicher.

gerne beim nächsten Mal einfach eine Suggestion machen @paternax

2020-10-07 10:04 UTC, zero-24 commented on administrator/language/de-DE/com_csp.sys.ini
> +COM_CSP="Content Security Policy"
Ja war ein c&p fehler. Hab deinen gerade comittet.

2020-10-07 11:26 UTC, tecpromotion commented on administrator/language/de-DE/com_workflow.ini
> +COM_WORKFLOW_BASIC_WORKFLOW="Grundsätzlicher Workflow"
```suggestion
COM_WORKFLOW_BASIC_WORKFLOW="Basic-Workflow"
```

2020-10-07 16:43 UTC, tecpromotion commented on administrator/language/de-DE/com_csp.ini
> +COM_CSP_HEADING_CLIENT_ASC="Standort, aufsteigend"
```suggestion
COM_CSP_HEADING_CLIENT_ASC="Client aufsteigend"
```

2020-10-07 16:43 UTC, tecpromotion commented on administrator/language/de-DE/com_csp.ini
> +COM_CSP_HEADING_CLIENT_DESC="Standort, absteigend"
```suggestion
COM_CSP_HEADING_CLIENT_DESC="Client absteigend"
```

2020-10-07 16:47 UTC, tecpromotion commented
@zero-24 RTM from my site

2020-10-08 13:48 UTC, zero-24 commented on administrator/language/de-DE/com_csp.ini
> +COM_CSP_CONTENTSECURITYPOLICY_STYLE_HASHES_ENABLED_DESC="Einen kryptografischen Hash für alle inline-styles generieren, welche über die Joomla-API in die Seite geladen werden, und mittels Content-Sec
```suggestion
COM_CSP_CONTENTSECURITYPOLICY_STYLE_HASHES_ENABLED_DESC="Einen kryptografischen Hash für alle inline-styles generieren, welche über die Joomla-API in die Seite geladen werden, und mittels Content-Security-Policy freigeben. Die Angabe von Hashes führt dazu, dass ein moderner Browser 'unsafe-inline' ignoriert."
```

2020-10-08 13:49 UTC, zero-24 approved these changes

2020-10-08 13:49 UTC, merged

2020-10-08 13:50 UTC, zero-24 commented
PS hab nur vorher einen Typo mit einem doppelten `"` gefixt. Danke 👍